from pathlib import Path
p=Path('app/src/main/java/com/kulanoglu/borsaradar/MainActivity.java')
s=p.read_text(encoding='utf-8')
# v117: one authoritative market state per radar screen; switch instantly, scan only on explicit button.
# Override selector generated by older patches so v97 main/hourly state cannot be overwritten by legacy radarMarketChoice.
a=s.find('private LinearLayout radarMarketSelector(final boolean hourly)')
if a>=0:
    b=s.find('\n    private ',a+10)
    if b<0:b=len(s)
    new='''private LinearLayout radarMarketSelector(final boolean hourly){
        final android.content.SharedPreferences sp=getSharedPreferences(PREFS,Context.MODE_PRIVATE);
        final int selected=sp.getInt(hourly?"radar_market_hourly":"radar_market_main",hourly?radarMarketChoiceHourly:radarMarketChoiceMain);
        if(hourly)radarMarketChoiceHourly=selected;else radarMarketChoiceMain=selected;
        radarMarketChoice=selected;
        LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);
        String[] labels={"BIST","ALMANYA","ABD","TÜMÜ"};
        for(int i=0;i<labels.length;i++){final int pick=i;Button bt=button(labels[i],selected==i?GREEN:NAVY2);bt.setOnClickListener(v->{
            int old=hourly?radarMarketChoiceHourly:radarMarketChoiceMain;
            saveRadarMarketSnapshot(old);
            if(hourly)radarMarketChoiceHourly=pick;else radarMarketChoiceMain=pick;
            radarMarketChoice=pick;
            sp.edit().putInt(hourly?"radar_market_hourly":"radar_market_main",pick).apply();
            restoreRadarMarketSnapshot(pick);
            if(hourly)showHourlyRadar();else showRadar();
        });row.addView(bt,new LinearLayout.LayoutParams(0,-2,1));}
        return row;
    }
'''
    s=s[:a]+new+s[b:]
# Ensure showRadar/showHourly set the active market before rendering header/results.
for method,field,key in [('showRadar()','radarMarketChoiceMain','radar_market_main'),('showHourlyRadar()','radarMarketChoiceHourly','radar_market_hourly')]:
    a=s.find('private void '+method)
    if a>=0:
        brace=s.find('{',a)+1
        ins='\n        '+field+'=getSharedPreferences(PREFS,Context.MODE_PRIVATE).getInt("'+key+'",'+field+');radarMarketChoice='+field+';restoreRadarMarketSnapshot(radarMarketChoice);'
        if ins.strip() not in s[brace:brace+400]:s=s[:brace]+ins+s[brace:]
# Explicit scan must scan currently visible market, not stale portfolio/profile market.
a=s.find('private void scanRadar()')
if a>=0:
    brace=s.find('{',a)+1
    ins='\n        radarMarketChoice=radarMarketChoiceMain; final int scanMarket=radarMarketChoice;'
    if 'final int scanMarket=' not in s[brace:brace+300]:s=s[:brace]+ins+s[brace:]
# Portfolio: switching profile must persist selected market, load that bucket, then render.
a=s.find('private LinearLayout portfolioMarketSelector()')
if a>=0:
    b=s.find('\n    private ',a+10)
    if b<0:b=len(s)
    new='''private LinearLayout portfolioMarketSelector(){
        LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);
        String[] labels={"BIST","ALMANYA","ABD"}; final int current=primaryMarket();
        for(int i=0;i<3;i++){final int target=i;Button bt=button(labels[i],current==i?GREEN:NAVY2);bt.setOnClickListener(v->{
            if(target==primaryMarket())return;
            try{getSharedPreferences(PREFS,Context.MODE_PRIVATE).edit().putInt("primary_market",target).putInt("active_profile",target).commit();holdingSignals.clear();holdingContexts.clear();loadPortfolio();main.post(this::showPortfolio);}catch(Throwable ex){Toast.makeText(this,"Portföy geçişi açılamadı",Toast.LENGTH_LONG).show();}
        });row.addView(bt,new LinearLayout.LayoutParams(0,-2,1));}return row;
    }
'''
    s=s[:a]+new+s[b:]
# Real portfolio add: after writing symbol to its actual market bucket, keep it there and render that bucket.
# v105 already writes portfolio_targetMarket; ensure preferences are committed before load/render.
s=s.replace('.putInt("active_profile",targetMarket).putInt("primary_market",targetMarket).commit();loadPortfolio();Toast.makeText(this,s+" gerçek portföye eklendi"', '.putInt("active_profile",targetMarket).putInt("primary_market",targetMarket).commit();holdings.clear();loadPortfolio();Toast.makeText(this,s+" gerçek portföye eklendi"')
p.write_text(s,encoding='utf-8')
