from pathlib import Path
p=Path('app/src/main/java/com/kulanoglu/borsaradar/MainActivity.java')
s=p.read_text(encoding='utf-8')
# The first detail shell may render before candles arrive. When a timeframe/chart fetch finishes,
# rerender the detail using the newly loaded candles so the quote card and plan share the same price.
needle='chart.setData(candles);'
if needle in s:
    s=s.replace(needle, needle+'\n                if(candles!=null && !candles.isEmpty() && candles.get(candles.size()-1).close>0){ final java.util.List<Candle> freshCandles=candles; runOnUiThread(()->{ try{ renderStockDetail(symbol,r,freshCandles); }catch(Exception ignored){} }); }',1)
# Common alternative chart variable name generated by older patches.
needle2='chart.setCandles(candles);'
if needle2 in s and 'freshCandles=candles' not in s:
    s=s.replace(needle2, needle2+'\n                if(candles!=null && !candles.isEmpty() && candles.get(candles.size()-1).close>0){ final java.util.List<Candle> freshCandles=candles; runOnUiThread(()->{ try{ renderStockDetail(symbol,r,freshCandles); }catch(Exception ignored){} }); }',1)
p.write_text(s,encoding='utf-8')
