package com.kulanoglu.borsaradar;
import org.json.JSONArray;import org.json.JSONObject;import java.util.*;
public final class PortfolioBook{
 public static final class Position{public final String id,symbol,signal,reason;public final double qty,price;public final long date;Position(String i,String s,double q,double p,long d,String g,String r){id=i;symbol=s;qty=q;price=p;date=d;signal=g==null||g.isEmpty()?"—":g;reason=r==null?"":r;}}
 public static final class Holding{public final String symbol;public final double qty,avgCost,cost;public final long firstDate;Holding(String s,double q,double c,long d){symbol=s;qty=q;cost=c;avgCost=q>0?c/q:0;firstDate=d;}}
 public static final class GroupStat{public int count,winners;public double sumReturnPct;public double avgReturnPct(){return count==0?Double.NaN:sumReturnPct/count;}public double winRatePct(){return count==0?Double.NaN:100d*winners/count;}}
 public static final class Stats{public double cost,value,pl,plPct;public int priced,missing;public final Map<String,GroupStat>bySignal=new LinkedHashMap<>();}
 private final List<Position>positions=new ArrayList<>();private long seq=0;
 public synchronized List<Position>positions(){return new ArrayList<>(positions);}public synchronized boolean isEmpty(){return positions.isEmpty();}
 public synchronized String add(String symbol,double qty,double price,long dateMillis,String signal,String reason){if(symbol==null)return null;String s=symbol.trim().toUpperCase(Locale.ROOT);if(s.isEmpty()||!(qty>0)||!(price>0)||Double.isNaN(qty)||Double.isNaN(price))return null;String id=Long.toString(dateMillis,36)+"-"+(++seq)+"-"+Long.toString(System.nanoTime()%100000,36);positions.add(new Position(id,s,qty,price,dateMillis,signal,reason));return id;}
 public synchronized boolean remove(String id){for(int i=0;i<positions.size();i++)if(positions.get(i).id.equals(id)){positions.remove(i);return true;}return false;}
 public synchronized List<Holding>holdings(){Map<String,double[]>m=new LinkedHashMap<>();Map<String,Long>first=new LinkedHashMap<>();for(Position p:positions){double[]a=m.get(p.symbol);if(a==null){a=new double[2];m.put(p.symbol,a);first.put(p.symbol,p.date);}a[0]+=p.qty;a[1]+=p.qty*p.price;if(p.date<first.get(p.symbol))first.put(p.symbol,p.date);}List<Holding>o=new ArrayList<>();for(Map.Entry<String,double[]>e:m.entrySet())o.add(new Holding(e.getKey(),e.getValue()[0],e.getValue()[1],first.get(e.getKey())));return o;}
 public synchronized Stats stats(Map<String,Double>prices){Stats st=new Stats();for(Position p:positions){Double now=prices==null?null:prices.get(p.symbol);if(now==null||!(now>0)){st.missing++;continue;}st.priced++;st.cost+=p.qty*p.price;st.value+=p.qty*now;double ret=(now/p.price-1)*100;GroupStat g=st.bySignal.get(p.signal);if(g==null){g=new GroupStat();st.bySignal.put(p.signal,g);}g.count++;g.sumReturnPct+=ret;if(ret>0)g.winners++;}st.pl=st.value-st.cost;st.plPct=st.cost>0?st.pl/st.cost*100:0;return st;}
 public synchronized String toJson(){JSONArray a=new JSONArray();try{for(Position p:positions){JSONObject o=new JSONObject();o.put("id",p.id);o.put("s",p.symbol);o.put("q",p.qty);o.put("p",p.price);o.put("d",p.date);o.put("g",p.signal);o.put("r",p.reason);a.put(o);}}catch(Exception ignored){}return a.toString();}
 public static PortfolioBook fromJson(String json){PortfolioBook b=new PortfolioBook();if(json==null||json.trim().isEmpty())return b;try{JSONArray a=new JSONArray(json);for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;String s=o.optString("s","").trim().toUpperCase(Locale.ROOT);double q=o.optDouble("q",Double.NaN),p=o.optDouble("p",Double.NaN);if(s.isEmpty()||!(q>0)||!(p>0))continue;String id=o.optString("id","");if(id.isEmpty())id="x"+(++b.seq);b.positions.add(new Position(id,s,q,p,o.optLong("d",0L),o.optString("g","—"),o.optString("r","")));}}catch(Exception ignored){}return b;}
}