package com.kulanoglu.borsaradar;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Path;
import android.view.View;
import android.view.MotionEvent;
import android.view.ScaleGestureDetector;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

public final class PriceChartView extends View {
    private final List<MarketDataService.Candle> data;
    private final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);
    private final String label;
    private int selectedIndex=-1;
    private float touchX=-1;
    private int visibleCount=0;
    private int visibleEnd=-1;
    private float downX=-1,lastX=-1;
    private long lastTapAt=0;
    private float lastTapX=-1000,lastTapY=-1000;
    private float legendEmaRight,legendBbRight,legendVwapRight,legendLevelsRight,legendVolumeRight,legendChangeRight,legendMomentumRight,legendSignalsRight,legendTrendRight;
    private boolean panning=false;
    private final ScaleGestureDetector scaleDetector;
    private boolean showEma=true,showBands=true,showVwap=true,showLevels=true;
    private boolean showVolume=true;
    private boolean showChangeLine=true;
    private boolean showMomentum=false;
    private boolean showSignals=false;
    private boolean showTrendLine=true;
    private boolean showEma50=false;
    public PriceChartView(Context c,List<MarketDataService.Candle>d){this(c,d,"1 GÜN");}
    public PriceChartView(Context c,List<MarketDataService.Candle>d,String l){super(c);data=d;label=l;visibleCount=d==null?0:d.size();visibleEnd=d==null?-1:d.size()-1;scaleDetector=new ScaleGestureDetector(c,new ScaleGestureDetector.SimpleOnScaleGestureListener(){@Override public boolean onScale(ScaleGestureDetector detector){if(data==null||data.size()<2)return false;int oldCount=visibleCount,next=Math.round(oldCount/detector.getScaleFactor());int minVisible=Math.min(8,data.size());next=Math.max(minVisible,Math.min(data.size(),next));float left=getPaddingLeft()+dp(3),right=getWidth()-getPaddingRight()-dp(64);float frac=Math.max(0f,Math.min(1f,(detector.getFocusX()-left)/Math.max(1f,right-left)));int oldStart=Math.max(0,visibleEnd-oldCount+1),focusIndex=Math.max(oldStart,Math.min(visibleEnd,oldStart+Math.round((oldCount-1)*frac)));visibleCount=next;int newStart=focusIndex-Math.round((next-1)*frac);newStart=Math.max(0,Math.min(data.size()-next,newStart));visibleEnd=newStart+next-1;selectedIndex=-1;invalidate();return true;}});setMinimumHeight(dp(350));setBackgroundColor(Color.rgb(9,30,54));setPadding(dp(12),dp(18),dp(12),dp(18));setContentDescription("Etkileşimli fiyat grafiği. Sürükle, yakınlaştır ve mum seç.");}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    @Override protected void onDraw(Canvas canvas){super.onDraw(canvas);if(data==null||data.size()<2)return;if(visibleEnd<0||visibleEnd>=data.size())visibleEnd=data.size()-1;if(visibleCount<=0)visibleCount=data.size();visibleCount=Math.max(2,Math.min(visibleCount,data.size()));int start=Math.max(0,visibleEnd-visibleCount+1),count=visibleEnd-start+1;String symbol=data.get(visibleEnd).symbol,cur=currencySymbol(symbol);float left=getPaddingLeft()+dp(3),right=getWidth()-getPaddingRight()-dp(64),top=getPaddingTop()+dp(52),priceBottom=getHeight()-getPaddingBottom()-dp(105),volTop=priceBottom+dp(12),volBottom=getHeight()-getPaddingBottom()-dp(48);double min=Double.MAX_VALUE,max=-Double.MAX_VALUE,maxVol=0;for(int i=start;i<=visibleEnd;i++){MarketDataService.Candle c=data.get(i);min=Math.min(min,c.low);max=Math.max(max,c.high);maxVol=Math.max(maxVol,c.volume);}if(max<=min)max=min+1;double dataMin=min,dataMax=max;double rawSpan=dataMax-dataMin,padRange=Math.max(rawSpan*.06,Math.abs(dataMax)*.001);min=dataMin-padRange;max=dataMax+padRange;
        paint.setStrokeWidth(dp(1));paint.setTextSize(dp(9));paint.setColor(Color.rgb(48,72,101));for(int i=0;i<=4;i++){float yy=top+(priceBottom-top)*i/4f;canvas.drawLine(left,yy,right,yy,paint);double raw=max-(max-min)*i/4.0;String pv=priceFmt(displayValue(raw,symbol))+" "+cur;paint.setColor(Color.rgb(190,207,226));canvas.drawText(pv,right+dp(5),yy+dp(4),paint);paint.setColor(Color.rgb(48,72,101));}
        float slot=(right-left)/Math.max(1,count);drawVerticalGrid(canvas,left,right,top,priceBottom,start,count);drawRangeStats(canvas,left,top,start);float body=Math.max(dp(2),Math.min(dp(11),slot*(count>120?.48f:.56f)));for(int j=0;j<count;j++){MarketDataService.Candle c=data.get(start+j);float x=left+slot*(j+.5f);float yh=y(c.high,min,max,top,priceBottom),yl=y(c.low,min,max,top,priceBottom),yo=y(c.open,min,max,top,priceBottom),yc=y(c.close,min,max,top,priceBottom);int col=c.close>=c.open?Color.rgb(22,190,135):Color.rgb(235,65,85);paint.setColor(col);paint.setStrokeWidth(dp(1));canvas.drawLine(x,yh,x,yl,paint);paint.setStyle(Paint.Style.FILL);canvas.drawRect(x-body/2,Math.min(yo,yc),x+body/2,Math.max(Math.min(yo,yc)+dp(1),Math.max(yo,yc)),paint);if(showVolume&&maxVol>0){float vh=(float)(c.volume/maxVol)*(volBottom-volTop);paint.setColor(Color.argb(150,Color.red(col),Color.green(col),Color.blue(col)));canvas.drawRect(x-body/2,volBottom-vh,x+body/2,volBottom,paint);}}
        if(showChangeLine){double baseLine=data.get(start).close;float by=y(baseLine,min,max,top,priceBottom);paint.setColor(Color.rgb(110,130,150));paint.setStrokeWidth(dp(1));canvas.drawLine(left,by,right,by,paint);paint.setTextSize(dp(9));String bt="BAZ "+priceFmt(displayValue(baseLine,symbol));paint.setColor(Color.rgb(150,170,192));canvas.drawText(bt,right-paint.measureText(bt)-dp(4),Math.max(top+dp(10),by-dp(3)),paint);}if(showEma){drawEma(canvas,5,start,count,left,right,min,max,top,priceBottom,Color.rgb(255,193,7));drawEma(canvas,9,start,count,left,right,min,max,top,priceBottom,Color.rgb(77,208,225));drawEma(canvas,20,start,count,left,right,min,max,top,priceBottom,Color.rgb(186,104,200));if(showEma50)drawEma(canvas,50,start,count,left,right,min,max,top,priceBottom,Color.rgb(255,138,101));}if(showBands&&count>=20)drawBollinger(canvas,20,start,count,left,right,min,max,top,priceBottom);if(showVwap)drawVwap(canvas,start,count,left,right,min,max,top,priceBottom);if(showLevels&&count<=260)drawSupportResistance(canvas,start,count,left,right,min,max,top,priceBottom);drawHighLowLabels(canvas,left,right,top,priceBottom,dataMin,dataMax,symbol,cur);if(showMomentum&&count<=120)drawMomentumBadge(canvas,left,priceBottom,start,visibleEnd);if(showSignals&&count<=120)drawSignalMarkers(canvas,start,count,left,right,min,max,top,priceBottom);drawTrendCue(canvas,left,right,top,start,visibleEnd,symbol);if(showTrendLine&&count>=8)drawTrendLine(canvas,start,count,left,right,min,max,top,priceBottom);if(count<=180)drawGapMarkers(canvas,start,count,left,right,min,max,top,priceBottom);
        paint.setTextSize(dp(11));paint.setColor(Color.WHITE);paint.setFakeBoldText(true);canvas.drawText(label+" • "+count+" MUM",left,dp(24),paint);paint.setFakeBoldText(false);drawLegend(canvas,left,dp(43));double last=data.get(visibleEnd).close,base=data.get(start).close,pct=base==0?0:(last-base)/base*100.0;String latest="SON "+priceFmt(displayValue(last,symbol))+" "+cur+"  "+(pct>=0?"+":"")+String.format(Locale.US,"%.2f%%",pct);paint.setColor(pct>=0?Color.rgb(22,190,135):Color.rgb(235,65,85));canvas.drawText(latest,right-paint.measureText(latest),dp(40),paint);
        drawLastPrice(canvas,left,right,top,priceBottom,min,max,symbol,cur);
        if(selectedIndex>=start && selectedIndex<=visibleEnd)drawCrosshair(canvas,left,right,top,priceBottom,volBottom,start,count,min,max,symbol,cur);
        if(showVolume){drawVolumeAverage(canvas,start,count,left,right,volTop,volBottom,maxVol);drawVolumeHeader(canvas,left,right,volTop,maxVol);}drawTimeScale(canvas,left,right,volBottom,start,count);
    }
    @Override public boolean onTouchEvent(MotionEvent e){
        if(data==null||data.isEmpty())return false;
        scaleDetector.onTouchEvent(e);
        if(scaleDetector.isInProgress())return true;
        if(e.getAction()==MotionEvent.ACTION_DOWN){float lx=e.getX(),ly=e.getY();if(toggleLegendAt(lx,ly)){selectedIndex=-1;invalidate();return true;}downX=lastX=touchX=lx;panning=false;return true;}
        if(e.getAction()==MotionEvent.ACTION_MOVE){
            touchX=e.getX();
            float left=getPaddingLeft()+dp(3),right=getWidth()-getPaddingRight()-dp(55);
            int start=Math.max(0,visibleEnd-visibleCount+1),count=Math.max(1,visibleEnd-start+1);
            float slot=(right-left)/count,dx=touchX-lastX;
            if(Math.abs(touchX-downX)>dp(12)&&visibleCount<data.size()){
                int shift=Math.round(-dx/Math.max(1f,slot));
                if(shift!=0){visibleEnd=Math.max(visibleCount-1,Math.min(data.size()-1,visibleEnd+shift));panning=true;selectedIndex=-1;lastX=touchX;invalidate();return true;}
            }
            selectedIndex=Math.max(start,Math.min(visibleEnd,start+(int)((touchX-left)/Math.max(1f,slot))));
            lastX=touchX;invalidate();return true;
        }
        if(e.getAction()==MotionEvent.ACTION_UP){if(!panning){long now=System.currentTimeMillis();if(now-lastTapAt<320&&Math.abs(e.getX()-lastTapX)<dp(28)&&Math.abs(e.getY()-lastTapY)<dp(28)){visibleCount=data.size();visibleEnd=data.size()-1;selectedIndex=-1;touchX=-1;invalidate();}else performClick();lastTapAt=now;lastTapX=e.getX();lastTapY=e.getY();}else{selectedIndex=-1;touchX=-1;invalidate();}downX=lastX=-1;panning=false;return true;}
        return true;
    }
    @Override public boolean performClick(){super.performClick();return true;}
    private void drawLastPrice(Canvas canvas,float left,float right,float top,float bottom,double min,double max,String symbol,String cur){
        double last=data.get(visibleEnd).close;float yy=y(last,min,max,top,bottom);
        paint.setColor(Color.rgb(240,180,40));paint.setStrokeWidth(dp(1));for(float xx=left;xx<right;xx+=dp(8))canvas.drawLine(xx,yy,Math.min(right,xx+dp(4)),yy,paint);
        paint.setTextSize(dp(10));String t=priceFmt(displayValue(last,symbol))+" "+cur;float pad=dp(4),tw=paint.measureText(t);paint.setColor(Color.rgb(240,180,40));canvas.drawRect(right+dp(2),yy-dp(10),right+dp(2)+tw+pad*2,yy+dp(5),paint);paint.setColor(Color.rgb(9,30,54));paint.setFakeBoldText(true);canvas.drawText(t,right+dp(2)+pad,yy+dp(2),paint);paint.setFakeBoldText(false);
    }
    private void drawCrosshair(Canvas canvas,float left,float right,float top,float priceBottom,float volBottom,int start,int count,double min,double max,String symbol,String cur){
        MarketDataService.Candle c=data.get(selectedIndex);float slot=(right-left)/Math.max(1,count);float x=left+slot*((selectedIndex-start)+.5f);float yy=y(c.close,min,max,top,priceBottom);
        paint.setColor(Color.argb(24,210,220,230));canvas.drawRect(Math.max(left,x-slot*.5f),top,Math.min(right,x+slot*.5f),volBottom,paint);paint.setColor(Color.argb(180,210,220,230));paint.setStrokeWidth(dp(1));for(float py=top;py<volBottom;py+=dp(8))canvas.drawLine(x,py,x,Math.min(volBottom,py+dp(4)),paint);for(float px=left;px<right;px+=dp(8))canvas.drawLine(px,yy,Math.min(right,px+dp(4)),yy,paint);
        paint.setTextSize(dp(9));String cp=priceFmt(displayValue(c.close,symbol));float cpw=paint.measureText(cp),cpp=dp(3);paint.setColor(Color.rgb(210,220,230));canvas.drawRect(right+dp(2),yy-dp(8),right+dp(2)+cpw+cpp*2,yy+dp(5),paint);paint.setColor(Color.rgb(9,30,54));canvas.drawText(cp,right+dp(2)+cpp,yy+dp(2),paint);
        paint.setTextSize(dp(10));paint.setColor(Color.WHITE);
        double prevClose=selectedIndex>0?data.get(selectedIndex-1).close:c.open;double candlePct=prevClose==0?0:(c.close/prevClose-1.0)*100.0;double rangePct=c.low==0?0:(c.high/c.low-1.0)*100.0;double bodyPct=c.open==0?0:(c.close/c.open-1.0)*100.0;double upperWick=Math.max(0,c.high-Math.max(c.open,c.close)),lowerWick=Math.max(0,Math.min(c.open,c.close)-c.low),body=Math.abs(c.close-c.open);String wick=body<=0?"Fitil nötr":upperWick>body*1.5&&upperWick>lowerWick*1.3?"Üst fitil":lowerWick>body*1.5&&lowerWick>upperWick*1.3?"Alt fitil":"Fitil dengeli";double volAvg=0;int volN=0;for(int vi=Math.max(0,selectedIndex-10);vi<selectedIndex;vi++){volAvg+=data.get(vi).volume;volN++;}volAvg=volN==0?c.volume:volAvg/volN;String volCue=volAvg<=0?"Hac nötr":c.volume>=volAvg*1.5?"Hac yüksek":c.volume<=volAvg*.65?"Hac düşük":"Hac normal";double relVol=volAvg<=0?1.0:c.volume/volAvg;String pressure=candlePct>0.15&&relVol>=1.5?"Alım baskısı":candlePct<-0.15&&relVol>=1.5?"Satış baskısı":Math.abs(candlePct)<0.15&&relVol>=1.5?"Yüksek hacim/nötr":"Denge";String rejection=upperWick>body*1.5&&relVol>=1.2?"Yukarı red":lowerWick>body*1.5&&relVol>=1.2?"Aşağı red":"";double priorHigh=-Double.MAX_VALUE,priorLow=Double.MAX_VALUE;for(int bi=Math.max(0,selectedIndex-10);bi<selectedIndex;bi++){priorHigh=Math.max(priorHigh,data.get(bi).high);priorLow=Math.min(priorLow,data.get(bi).low);}String breakout=selectedIndex>0&&c.close>priorHigh&&relVol>=1.2?"Hacimli yukarı kırılım":selectedIndex>0&&c.close<priorLow&&relVol>=1.2?"Hacimli aşağı kırılım":"";String info="A "+priceFmt(displayValue(c.open,symbol))+"  Y "+priceFmt(displayValue(c.high,symbol))+"  D "+priceFmt(displayValue(c.low,symbol))+"  K "+priceFmt(displayValue(c.close,symbol))+" "+cur+"  "+String.format(Locale.US,"%+.2f%%",candlePct)+"  Hac "+compact(c.volume)+" x"+String.format(Locale.US,"%.1f",relVol);
        float pad=dp(6),boxTop=top-dp(20),boxBottom=top-dp(3),available=Math.max(dp(80),right-left-pad*2);if(paint.measureText(info)>available){paint.setTextSize(dp(9));}float boxRight=Math.min(right,left+paint.measureText(info)+pad*2);paint.setColor(Color.argb(220,18,42,68));canvas.drawRect(left,boxTop,boxRight,boxBottom,paint);paint.setColor(Color.WHITE);canvas.save();canvas.clipRect(left,boxTop,right,boxBottom);canvas.drawText(info,left+pad,top-dp(8),paint);canvas.restore();
        SimpleDateFormat sdf=new SimpleDateFormat("dd.MM.yy HH:mm",Locale.getDefault());String dt=sdf.format(new Date(c.time*1000L));float tw=paint.measureText(dt);canvas.drawText(dt,Math.max(left,Math.min(x-tw/2,right-tw)),getHeight()-dp(25),paint);
    }
    private String priceFmt(double v){double a=Math.abs(v);if(a>=1000)return String.format(Locale.US,"%.1f",v);if(a>=100)return String.format(Locale.US,"%.2f",v);if(a>=1)return String.format(Locale.US,"%.2f",v);return String.format(Locale.US,"%.4f",v);}
    private String compact(double v){if(v>=1000000)return String.format(Locale.US,"%.1fM",v/1000000d);if(v>=1000)return String.format(Locale.US,"%.1fK",v/1000d);return String.format(Locale.US,"%.0f",v);}
    private void drawVerticalGrid(Canvas canvas,float left,float right,float top,float bottom,int start,int count){paint.setStrokeWidth(dp(1));paint.setColor(Color.rgb(36,58,82));int ticks=Math.min(5,Math.max(2,count));for(int i=0;i<ticks;i++){float x=left+(right-left)*i/(float)(ticks-1);canvas.drawLine(x,top,x,bottom,paint);}}
    private void drawRangeStats(Canvas canvas,float left,float top,int start){double first=data.get(start).close,last=data.get(visibleEnd).close;double pct=first==0?0:(last-first)/first*100.0;paint.setTextSize(dp(9));paint.setColor(pct>=0?Color.rgb(22,190,135):Color.rgb(235,65,85));long span=Math.max(0,data.get(visibleEnd).time-data.get(start).time);String dur=span<3600?(span/60)+" dk":span<86400?(span/3600)+" sa":span<2592000?(span/86400)+" gün":String.format(Locale.US,"%.1f ay",span/2592000d);String s=(pct>=0?"+":"")+String.format(Locale.US,"%.2f%%",pct)+"  •  "+visibleCount+" mum  •  "+dur;canvas.drawText(s,left,top+dp(24),paint);}
    private void drawGapMarkers(Canvas canvas,int start,int count,float left,float right,double min,double max,float top,float bottom){if(count<2)return;float slot=(right-left)/Math.max(1,count);paint.setTextSize(dp(8));for(int j=1;j<count;j++){MarketDataService.Candle p=data.get(start+j-1),q=data.get(start+j);if(p.close==0)continue;double gap=(q.open/p.close-1)*100.0;if(Math.abs(gap)<1.0)continue;float x=left+slot*(j+.5f),yy=y(q.open,min,max,top,bottom);paint.setColor(gap>0?Color.rgb(22,190,135):Color.rgb(235,65,85));canvas.drawText(gap>0?"G↑":"G↓",x-dp(5),gap>0?yy+dp(12):yy-dp(5),paint);}}
    private void drawTrendLine(Canvas canvas,int start,int count,float left,float right,double min,double max,float top,float bottom){if(count<3)return;double sx=0,sy=0,sxx=0,sxy=0;for(int j=0;j<count;j++){double v=data.get(start+j).close;sx+=j;sy+=v;sxx+=j*j;sxy+=j*v;}double den=count*sxx-sx*sx;if(Math.abs(den)<1e-9)return;double slope=(count*sxy-sx*sy)/den,intercept=(sy-slope*sx)/count;float slot=(right-left)/Math.max(1,count),x1=left+slot*.5f,x2=left+slot*(count-.5f),y1=y(intercept,min,max,top,bottom),y2=y(intercept+slope*(count-1),min,max,top,bottom);paint.setColor(Color.rgb(120,170,255));paint.setStrokeWidth(dp(1));canvas.drawLine(x1,y1,x2,y2,paint);}
    private void drawTrendCue(Canvas canvas,float left,float right,float top,int start,int end,String symbol){if(end-start<5)return;int n=Math.min(20,end-start+1);double first=data.get(end-n+1).close,last=data.get(end).close;double pct=first==0?0:(last/first-1)*100.0,hh=-Double.MAX_VALUE,ll=Double.MAX_VALUE;for(int i=end-n+1;i<=end;i++){hh=Math.max(hh,data.get(i).high);ll=Math.min(ll,data.get(i).low);}double pos=hh<=ll?50:(last-ll)/(hh-ll)*100.0;String t=pct>1.0?"Kısa trend ↑":pct<-1.0?"Kısa trend ↓":"Kısa trend →";t+="  "+String.format(Locale.US,"%+.2f%%",pct)+"  Konum "+String.format(Locale.US,"%.0f%%",pos);paint.setTextSize(dp(9));paint.setColor(pct>0?Color.rgb(22,190,135):pct<0?Color.rgb(235,65,85):Color.rgb(170,185,202));float w=paint.measureText(t);canvas.drawText(t,Math.max(left,right-w),top+dp(11),paint);}
    private void drawSignalMarkers(Canvas canvas,int start,int count,float left,float right,double min,double max,float top,float bottom){if(count<12)return;float slot=(right-left)/Math.max(1,count);paint.setTextSize(dp(9));for(int j=10;j<count;j++){int i=start+j;MarketDataService.Candle cur=data.get(i);double hi=-Double.MAX_VALUE,lo=Double.MAX_VALUE,va=0;for(int k=i-10;k<i;k++){hi=Math.max(hi,data.get(k).high);lo=Math.min(lo,data.get(k).low);va+=data.get(k).volume;}va/=10.0;boolean up=cur.close>hi&&cur.volume>=va*1.2,down=cur.close<lo&&cur.volume>=va*1.2;if(!up&&!down)continue;float x=left+slot*(j+.5f);float yy=y(up?cur.low:cur.high,min,max,top,bottom);paint.setColor(up?Color.rgb(22,190,135):Color.rgb(235,65,85));canvas.drawText(up?"▲":"▼",x-dp(4),up?yy+dp(13):yy-dp(5),paint);paint.setTextSize(dp(7));String rv=String.format(Locale.US,"x%.1f",va<=0?1.0:cur.volume/va);canvas.drawText(rv,x-dp(7),up?yy+dp(22):yy-dp(13),paint);paint.setTextSize(dp(9));}}
    private void drawMomentumBadge(Canvas canvas,float left,float bottom,int start,int end){if(end<=start)return;int up=0,down=0;double gain=0,loss=0;for(int i=Math.max(start+1,end-9);i<=end;i++){double d=data.get(i).close-data.get(i-1).close;if(d>0){up++;gain+=d;}else if(d<0){down++;loss-=d;}}String state=up>=down+2?"Momentum ↑":down>=up+2?"Momentum ↓":"Momentum →";double ratio=loss<=0?(gain>0?9.99:1.0):Math.min(9.99,gain/loss);double first=data.get(Math.max(start,end-9)).close,last=data.get(end).close,momPct=first==0?0:(last/first-1)*100.0;String t=state+"  "+String.format(Locale.US,"%+.2f%%",momPct)+"  "+up+"↑/"+down+"↓  G/K "+String.format(Locale.US,"%.2f",ratio);paint.setTextSize(dp(9));paint.setColor(up>=down?Color.rgb(22,190,135):Color.rgb(235,65,85));canvas.drawText(t,left,bottom-dp(5),paint);}
    private void drawVolumeAverage(Canvas canvas,int start,int count,float left,float right,float top,float bottom,double maxVol){if(count<3||maxVol<=0)return;int p=Math.min(10,count);float slot=(right-left)/Math.max(1,count);Path path=new Path();boolean begun=false;for(int j=p-1;j<count;j++){double sum=0;for(int k=j-p+1;k<=j;k++)sum+=Math.max(0,data.get(start+k).volume);double avg=sum/p;float x=left+slot*(j+.5f),yy=bottom-(float)(avg/maxVol)*(bottom-top);if(!begun){path.moveTo(x,yy);begun=true;}else path.lineTo(x,yy);}paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(dp(1));paint.setColor(Color.rgb(255,193,7));canvas.drawPath(path,paint);paint.setStyle(Paint.Style.FILL);}
    private void drawVolumeHeader(Canvas canvas,float left,float right,float volTop,double maxVol){paint.setStrokeWidth(dp(1));paint.setColor(Color.rgb(48,72,101));canvas.drawLine(left,volTop,right,volTop,paint);paint.setTextSize(dp(9));paint.setColor(Color.rgb(150,170,192));double lastVol=data.get(visibleEnd).volume;String t="HACİM  "+compact(lastVol)+"  •  MA10 sarı  •  Maks "+compact(maxVol);canvas.drawText(t,left,volTop+dp(10),paint);}
    private void drawTimeScale(Canvas canvas,float left,float right,float volBottom,int start,int count){paint.setTextSize(dp(10));paint.setColor(Color.rgb(190,207,226));int ticks=Math.min(5,Math.max(2,count));long span=Math.max(0,data.get(visibleEnd).time-data.get(start).time);String pattern=span<=2*86400L?"HH:mm":span<=120*86400L?"dd.MM":"MM.yy";SimpleDateFormat sdf=new SimpleDateFormat(pattern,Locale.getDefault());for(int i=0;i<ticks;i++){int idx=start+Math.round((count-1)*i/(float)(ticks-1));float x=left+(right-left)*i/(float)(ticks-1);String t=sdf.format(new Date(data.get(idx).time*1000L));float tw=paint.measureText(t);if(i==0)canvas.drawText(t,x,getHeight()-dp(8),paint);else if(i==ticks-1)canvas.drawText(t,x-tw,getHeight()-dp(8),paint);else canvas.drawText(t,x-tw/2,getHeight()-dp(8),paint);paint.setColor(Color.rgb(36,58,82));canvas.drawLine(x,volBottom+dp(2),x,getHeight()-dp(23),paint);paint.setColor(Color.rgb(190,207,226));}}
    private boolean toggleLegendAt(float tx,float ty){paint.setTextSize(dp(9));String[] names={"EMA","BB","VWAP","S/R","HAC","BAZ","MOM","SNY","TR"};float left=getPaddingLeft()+dp(3),x=left,rowY=dp(43),maxX=getWidth()-getPaddingRight()-dp(4);for(int i=0;i<names.length;i++){String t="● "+names[i];float tw=paint.measureText(t)+dp(12);if(x+tw>maxX&&x>left){x=left;rowY+=dp(13);}if(tx>=x&&tx<=x+tw&&ty>=rowY-dp(11)&&ty<=rowY+dp(4)){if(i==0)showEma=!showEma;else if(i==1)showBands=!showBands;else if(i==2)showVwap=!showVwap;else if(i==3)showLevels=!showLevels;else if(i==4)showVolume=!showVolume;else if(i==5)showChangeLine=!showChangeLine;else if(i==6)showMomentum=!showMomentum;else if(i==7)showSignals=!showSignals;else showTrendLine=!showTrendLine;return true;}x+=tw;}return false;}
    private void drawLegend(Canvas canvas,float left,float y){paint.setTextSize(dp(9));String[] names={"EMA","BB","VWAP","S/R","HAC","BAZ","MOM","SNY","TR"};boolean[] on={showEma,showBands,showVwap,showLevels,showVolume,showChangeLine,showMomentum,showSignals,showTrendLine};float x=left,rowY=y,maxX=getWidth()-getPaddingRight()-dp(4);for(int i=0;i<names.length;i++){String t=(on[i]?"● ":"○ ")+names[i];float tw=paint.measureText(t)+dp(12);if(x+tw>maxX&&x>left){x=left;rowY+=dp(13);}paint.setColor(on[i]?Color.WHITE:Color.rgb(105,120,138));canvas.drawText(t,x,rowY,paint);if(on[i]){paint.setStrokeWidth(dp(1));canvas.drawLine(x,rowY+dp(2),x+paint.measureText(t),rowY+dp(2),paint);}x+=tw;if(i==0)legendEmaRight=x;else if(i==1)legendBbRight=x;else if(i==2)legendVwapRight=x;else if(i==3)legendLevelsRight=x;else if(i==4)legendVolumeRight=x;else if(i==5)legendChangeRight=x;else if(i==6)legendMomentumRight=x;else if(i==7)legendSignalsRight=x;else legendTrendRight=x;}}
    private void drawHighLowLabels(Canvas canvas,float left,float right,float top,float bottom,double min,double max,String symbol,String cur){paint.setTextSize(dp(10));paint.setColor(Color.rgb(210,220,232));String hi="Y "+priceFmt(displayValue(max,symbol))+" "+cur,lo="D "+priceFmt(displayValue(min,symbol))+" "+cur;canvas.drawText(hi,left,top+dp(11),paint);canvas.drawText(lo,left,bottom-dp(5),paint);}
    private float y(double v,double min,double max,float top,float bottom){return bottom-(float)((v-min)/(max-min))*(bottom-top);}
    private void drawEma(Canvas canvas,int period,int start,int count,float left,float right,double min,double max,float top,float bottom,int color){if(count<period)return;double k=2.0/(period+1),e=data.get(start).close;Path p=new Path();float slot=(right-left)/Math.max(1,count);for(int j=0;j<count;j++){double c=data.get(start+j).close;e=j==0?c:c*k+e*(1-k);float x=left+slot*(j+.5f),yy=y(e,min,max,top,bottom);if(j==0)p.moveTo(x,yy);else p.lineTo(x,yy);}paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(dp(1));paint.setColor(color);canvas.drawPath(p,paint);paint.setStyle(Paint.Style.FILL);}
    private void drawBollinger(Canvas canvas,int period,int start,int count,float left,float right,double min,double max,float top,float bottom){if(count<period)return;Path up=new Path(),lo=new Path();float slot=(right-left)/Math.max(1,count);boolean begun=false;for(int j=period-1;j<count;j++){double sum=0,sq=0;for(int k=j-period+1;k<=j;k++){double v=data.get(start+k).close;sum+=v;sq+=v*v;}double mean=sum/period,sd=Math.sqrt(Math.max(0,sq/period-mean*mean));float x=left+slot*(j+.5f),yu=y(mean+2*sd,min,max,top,bottom),yl=y(mean-2*sd,min,max,top,bottom);if(!begun){up.moveTo(x,yu);lo.moveTo(x,yl);begun=true;}else{up.lineTo(x,yu);lo.lineTo(x,yl);}}paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(dp(1));paint.setColor(Color.rgb(120,144,156));canvas.drawPath(up,paint);canvas.drawPath(lo,paint);paint.setStyle(Paint.Style.FILL);}
    private void drawVwap(Canvas canvas,int start,int count,float left,float right,double min,double max,float top,float bottom){double pv=0,vol=0;Path p=new Path();float slot=(right-left)/Math.max(1,count);boolean begun=false;for(int j=0;j<count;j++){MarketDataService.Candle c=data.get(start+j);double v=Math.max(0,c.volume);if(v<=0)continue;pv+=((c.high+c.low+c.close)/3.0)*v;vol+=v;double vw=pv/vol;float x=left+slot*(j+.5f),yy=y(vw,min,max,top,bottom);if(!begun){p.moveTo(x,yy);begun=true;}else p.lineTo(x,yy);}if(!begun)return;paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(dp(1));paint.setColor(Color.rgb(38,198,218));canvas.drawPath(p,paint);paint.setStyle(Paint.Style.FILL);}
    private void drawSupportResistance(Canvas canvas,int start,int count,float left,float right,double min,double max,float top,float bottom){int n=Math.min(count,40);double support=Double.MAX_VALUE,resistance=-Double.MAX_VALUE;for(int j=count-n;j<count;j++){MarketDataService.Candle c=data.get(start+j);support=Math.min(support,c.low);resistance=Math.max(resistance,c.high);}float sy=y(support,min,max,top,bottom),ry=y(resistance,min,max,top,bottom);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(dp(1));paint.setColor(Color.rgb(46,204,113));canvas.drawLine(left,sy,right,sy,paint);paint.setColor(Color.rgb(255,99,71));canvas.drawLine(left,ry,right,ry,paint);paint.setStyle(Paint.Style.FILL);paint.setTextSize(dp(9));String symbol=data.get(visibleEnd).symbol,cur=currencySymbol(symbol);String st="D "+priceFmt(displayValue(support,symbol))+" "+cur,rt="R "+priceFmt(displayValue(resistance,symbol))+" "+cur;paint.setColor(Color.rgb(46,204,113));canvas.drawText(st,left+dp(4),Math.max(top+dp(10),sy-dp(3)),paint);paint.setColor(Color.rgb(255,99,71));canvas.drawText(rt,right-paint.measureText(rt)-dp(4),Math.max(top+dp(10),ry-dp(3)),paint);}
    private double displayValue(double v,String symbol){String n=MarketDataService.normalizeSymbol(symbol);if(n.endsWith(".IS")||n.endsWith(".DE"))return v;double rate=CurrencyService.usdToEur();return Double.isFinite(rate)?v*rate:v;}
    private String currencySymbol(String symbol){String n=MarketDataService.normalizeSymbol(symbol);return n.endsWith(".IS")?"₺":"€";}
    private String fmt(double v){return String.format(Locale.US,"%.2f",v);}
}
