package com.kulanoglu.borsaradar;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.Typeface;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.*;

public class ReferenceUiActivity extends Activity {
 private final int NAVY=Color.rgb(5,18,34), PANEL=Color.rgb(12,34,59), BLUE=Color.rgb(36,118,255), MUTED=Color.rgb(137,163,188), GREEN=Color.rgb(31,191,126), AMBER=Color.rgb(245,158,11), RED=Color.rgb(238,82,83);
 private LinearLayout body; private LinearLayout radarRows; private TextView radarProgress; private String radarFilter="Tümü"; private int screen=0; private String selectedSymbol="THYAO"; private String lastRadarSymbol="THYAO"; private int radarIndex=0; private boolean scanDone=false; private boolean radarLoading=false; private String scanMode="Teknik + Temel";
 private String selectedMarket="BIST";
 private ShortPulseEngine.Profile selectedProfile=ShortPulseEngine.Profile.BALANCED; private final java.util.ArrayList<String[]> cachedRadarRows=new java.util.ArrayList<>();
 private final java.util.HashMap<String,java.util.ArrayList<String[]>> radarCacheByMarket=new java.util.HashMap<>();
 private final java.util.HashMap<String,Boolean> scanDoneByMarket=new java.util.HashMap<>();
 private final String[] radarSymbols={"THYAO","BIMAS","TCELL","KRDMD","PETKM","ENERY","KCHOL","TUPRS","GARAN","AKBNK","YKBNK","SASA","FROTO","TTKOM","GWIND","AAGYO","DUNYH","KLRHO","EREGL","SISE","SAHOL","ISCTR","HALKB","VAKBN","TOASO","TAVHL","PGSUS","ARCLK","VESTL","MGROS","ULKER","AEFES","CCOLA","DOAS","EKGYO","OYAKC","KOZAL","KOZAA","IPEKE","ASTOR","ENKAI","HEKTS","GUBRF","ALARK","ODAS","KONTR","GESAN","EUPWR","MIATK","REEDR","TABGD","MAVI","MPARK","SOKM","TTRAK","OTKAR","KARSN","TMSN","AKSA","AKSEN","ZOREN","AYDEM","KCAER","CIMSA","AKCNS","BTCIM","BRISA","KORDS","LOGO","NETAS","KAREL","SELEC","ECILC","DEVA","TURSG","ANHYT","AGESA","TSKB","SKBNK","ALBRK","ISMEN","DOHOL","GLYHO","GSRAY","FENER","BJKAS"};
 private final String[] germanyRadarSymbols={"SAP.DE","SIE.DE","ALV.DE","DTE.DE","MBG.DE","BMW.DE","BAS.DE","IFX.DE","ADS.DE","DBK.DE","RWE.DE","MUV2.DE","VOW3.DE","HEN3.DE","BEI.DE","FRE.DE","HEI.DE","MTX.DE","QIA.DE","SY1.DE"};
 private final String[] usaRadarSymbols={"AAPL","MSFT","NVDA","AMZN","GOOGL","META","TSLA","AVGO","AMD","NFLX","JPM","V","MA","COST","WMT","KO","PEP","XOM","JNJ","ORCL"};
 private String[] radarUniverse(){if("Almanya".equals(selectedMarket))return germanyRadarSymbols;if("ABD".equals(selectedMarket))return usaRadarSymbols;if("Tümü".equals(selectedMarket)){String[] all=new String[radarSymbols.length+germanyRadarSymbols.length+usaRadarSymbols.length];System.arraycopy(radarSymbols,0,all,0,radarSymbols.length);System.arraycopy(germanyRadarSymbols,0,all,radarSymbols.length,germanyRadarSymbols.length);System.arraycopy(usaRadarSymbols,0,all,radarSymbols.length+germanyRadarSymbols.length,usaRadarSymbols.length);return all;}
 private String[][] featuredForMarket(){
  if("Almanya".equals(selectedMarket))return new String[][]{{"SAP.DE","","",""},{"SIE.DE","","",""},{"ALV.DE","","",""}};
  if("ABD".equals(selectedMarket))return new String[][]{{"NVDA","","",""},{"AAPL","","",""},{"MSFT","","",""}};
  if("Tümü".equals(selectedMarket))return new String[][]{{"THYAO","","",""},{"SAP.DE","","",""},{"NVDA","","",""}};
  return new String[][]{{"THYAO","","",""},{"BIMAS","","",""},{"TCELL","","",""}};
 }return radarSymbols;} private TextView livePrice,liveChange,liveTime,chartPrice,chartChange,computedSignal; private LinearLayout horizonSignals; private LinearLayout liveStats; private final java.util.concurrent.ExecutorService uiIo=java.util.concurrent.Executors.newSingleThreadExecutor();
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 private android.graphics.drawable.GradientDrawable bg(int c,int r){android.graphics.drawable.GradientDrawable g=new android.graphics.drawable.GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 private TextView t(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(null,Typeface.BOLD);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 private LinearLayout card(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);v.setPadding(dp(12),dp(10),dp(12),dp(10));v.setBackground(bg(PANEL,12));return v;}
 private void gap(int h){Space s=new Space(this);body.addView(s,new LinearLayout.LayoutParams(1,dp(h)));}
 private String companyName(String s){java.util.Map<String,String>m=new java.util.HashMap<>();m.put("THYAO","Türk Hava Yolları A.Ş.");m.put("BIMAS","BİM Birleşik Mağazalar");m.put("TCELL","Turkcell");m.put("ASELS","Aselsan");m.put("KRDMD","Kardemir D");m.put("PETKM","Petkim");m.put("ENERY","Enerya Enerji");m.put("KCHOL","Koç Holding");m.put("TUPRS","Tüpraş");m.put("GARAN","Garanti BBVA");m.put("AKBNK","Akbank");m.put("YKBNK","Yapı Kredi");m.put("SASA","SASA Polyester");m.put("NVDA","NVIDIA");return m.containsKey(s)?m.get(s):s;}
 private String currency(String s){return "NVDA".equals(s)||(!java.util.Arrays.asList(radarSymbols).contains(s)&&s.matches("[A-Z]{1,5}"))?" $":" ₺";}
 private void addCompactLiveQuote(){final TextView p=t("Veri yükleniyor…",27,Color.WHITE,true),ch=t("",14,MUTED,true);body.addView(p);body.addView(ch);final String symbol=selectedSymbol;uiIo.execute(()->{try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(symbol,"5d","5m",200);if(d==null||d.size()<2)return;double price=d.get(d.size()-1).close,prev=d.get(d.size()-2).close;MarketDataService.Spot sp=MarketDataService.latestSpot(symbol);if(sp!=null&&sp.price>0)price=sp.price;final double fp=price,fc=price-prev,pc=prev==0?0:(price-prev)/prev*100d;runOnUiThread(()->{if(!symbol.equals(selectedSymbol))return;p.setText(String.format(java.util.Locale.GERMANY,"%.2f%s",fp,currency(symbol)));ch.setText(String.format(java.util.Locale.GERMANY,"%+.2f (%+.2f%%)",fc,pc));ch.setTextColor(fc>=0?GREEN:RED);});}catch(Exception ignored){runOnUiThread(()->p.setText("Fiyat alınamadı"));}});}
 private TextView pill(String s,int color){TextView v=t(s,10,Color.WHITE,true);v.setGravity(Gravity.CENTER);v.setBackground(bg(color,9));v.setPadding(dp(8),0,dp(8),0);return v;}
 private void nav(LinearLayout root,int active){LinearLayout n=new LinearLayout(this);n.setBackgroundColor(Color.rgb(7,27,46));String[] a={"⌂\\nAna Sayfa","▥\\nPiyasalar","◎\\nRadar","▣\\nPortföy","•••\\nDiğer"};for(int i=0;i<5;i++){TextView v=t(a[i],9,i==active?BLUE:MUTED,i==active);v.setGravity(Gravity.CENTER);final int k=i;v.setOnClickListener(x->{if(k==0)showHome();else if(k==1)showRadar();else if(k==2)showRadar();else if(k==3)showPortfolio();else showMore();});n.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(n);}
 private LinearLayout detailRoot(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(10));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));return root;}
 private void stockHead(){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.addView(t("‹",24,Color.WHITE,true),new LinearLayout.LayoutParams(dp(28),dp(42)));TextView logo=pill("✈",RED);h.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);names.addView(t(selectedTicker,16,Color.WHITE,true));names.addView(t(companyName(selectedTicker),9,MUTED,false));h.addView(names,new LinearLayout.LayoutParams(0,dp(45),1));h.addView(t("＋  ★",19,Color.rgb(245,178,43),true),new LinearLayout.LayoutParams(dp(68),dp(42)));body.addView(h);body.addView(t("277,20 ₺",27,Color.WHITE,true));body.addView(t("+4,90  (+1,80%)",15,GREEN,true));body.addView(t("15.09.2026 14:32",9,MUTED,false));gap(8);LinearLayout tabs=new LinearLayout(this);String[] ts={"Genel","Grafik","Haber","KAP","Finansal"};for(int i=0;i<5;i++){TextView x=t(ts[i],10,i==0?Color.WHITE:MUTED,i==0);x.setGravity(Gravity.CENTER);final int k=i;x.setOnClickListener(v->{if(k==0)showDetail();else if(k==1)showChart();else if(k==2||k==3)showNews();else if(k==4)showFinancial();});tabs.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(tabs);gap(8);}
 @Override public void onCreate(Bundle b){super.onCreate(b);android.content.SharedPreferences p=getSharedPreferences("borsaradar",MODE_PRIVATE);lastRadarSymbol=p.getString("lastRadarSymbol","THYAO");selectedSymbol=lastRadarSymbol;scanDone=p.getBoolean("scanDone",false);scanMode=p.getString("scanMode","Teknik + Temel");selectedMarket=p.getString("selectedMarket","BIST");
  try{selectedProfile=ShortPulseEngine.Profile.valueOf(p.getString("selectedProfile","BALANCED"));}catch(Exception ignored){selectedProfile=ShortPulseEngine.Profile.BALANCED;}String screen=getIntent().getStringExtra("screen");if("detail".equals(screen))showDetail();else if("chart".equals(screen))showChart();else if("news".equals(screen))showNews();else if("financial".equals(screen))showFinancial();else if("radar".equals(screen))showRadar();else if("technical".equals(screen))showTechnical();else if("target".equals(screen))showTargetRisk();else if("portfolio".equals(screen))showPortfolio();else if("strategy".equals(screen))showStrategy();else if("more".equals(screen))showMore();else showHome();}
 @Override public void onBackPressed(){if(screen==4||screen==5||screen==6||screen==7||screen==8)showDetail();else if(screen==3)showRadar();else if(screen==2||screen==9||screen==10||screen==11)showHome();else super.onBackPressed();}
 private void showHome(){ screen=1;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);
  ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(14),dp(14),dp(14),dp(14));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);
  TextView mark=t("BR",12,Color.WHITE,true);mark.setGravity(Gravity.CENTER);mark.setBackground(bg(BLUE,10));head.addView(mark,new LinearLayout.LayoutParams(dp(34),dp(34)));
  LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);TextView name=t("BORSA RADAR",18,Color.WHITE,true);TextView sub=t("Akıllı piyasa takip merkezi",9,MUTED,false);brand.addView(name);brand.addView(sub);head.addView(brand,new LinearLayout.LayoutParams(0,dp(46),1));
  TextView bell=t("●",16,BLUE,true);bell.setGravity(Gravity.CENTER);head.addView(bell,new LinearLayout.LayoutParams(dp(36),dp(36)));body.addView(head);gap(10);
  TextView search=t("⌕   Hisse, endeks veya şirket ara",12,Color.rgb(190,207,222),false);search.setPadding(dp(12),0,dp(12),0);search.setBackground(bg(PANEL,12));body.addView(search,new LinearLayout.LayoutParams(-1,dp(44)));gap(8);
  LinearLayout markets=new LinearLayout(this);String[] ms={"BIST","Almanya","ABD","Tümü"};for(int i=0;i<4;i++){final String market=ms[i];boolean active=market.equals(selectedMarket);TextView x=t(market,11,active?Color.WHITE:MUTED,true);x.setGravity(Gravity.CENTER);x.setBackground(bg(active?BLUE:PANEL,10));x.setOnClickListener(v->{selectedMarket=market;getSharedPreferences("borsaradar",MODE_PRIVATE).edit().putString("selectedMarket",market).apply();java.util.ArrayList<String[]> oldCache=new java.util.ArrayList<>(cachedRadarRows);radarCacheByMarket.put(selectedMarket,oldCache);scanDoneByMarket.put(selectedMarket,scanDone);
 selectedMarket=market;java.util.ArrayList<String[]> next=radarCacheByMarket.get(market);cachedRadarRows.clear();if(next!=null)cachedRadarRows.addAll(next);scanDone=Boolean.TRUE.equals(scanDoneByMarket.get(market));showHome();});markets.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(markets);gap(14);
  body.addView(t("Stratejiler",15,Color.WHITE,true));gap(6);
  String[] a={"⚡  Hızlı Tarama\nAnlık fırsatlar","↗  Kısa Vade\nGünlük / saatlik","◆  Temettü\nDüzenli gelir","◎  Uzun Vade\nGüçlü şirketler"};for(int r=0;r<2;r++){LinearLayout row=new LinearLayout(this);for(int j=0;j<2;j++){LinearLayout c=card();TextView x=t(a[r*2+j],11,Color.WHITE,true);c.addView(x,new LinearLayout.LayoutParams(-1,-1));c.setOnClickListener(v->showStrategy());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(66),1);lp.setMargins(dp(3),dp(3),dp(3),dp(3));row.addView(c,lp);}body.addView(row);}gap(14);
  LinearLayout ttl=new LinearLayout(this);ttl.addView(t("Günün Öne Çıkanları",15,Color.WHITE,true),new LinearLayout.LayoutParams(0,dp(28),1));TextView all=t("Tümünü Gör  ›",10,BLUE,true);all.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);ttl.addView(all,new LinearLayout.LayoutParams(dp(100),dp(28)));body.addView(ttl);gap(5);
  String[][] stocks=featuredForMarket();for(String[] s:stocks){LinearLayout c=card();c.setOrientation(LinearLayout.HORIZONTAL);TextView code=t(s[0],13,Color.WHITE,true);if(s[0].equals("THYAO")){c.setOnClickListener(v->showDetail());code.setOnClickListener(v->showDetail());}c.addView(code,new LinearLayout.LayoutParams(0,dp(36),1));TextView p=t(s[1]+"   "+s[2],11,s[2].contains("-")?RED:GREEN,true);p.setGravity(Gravity.CENTER);c.addView(p,new LinearLayout.LayoutParams(dp(145),dp(36)));TextView sig=t(s[3],10,s[3].equals("AL")?GREEN:s[3].equals("SAT")?RED:Color.rgb(239,177,57),true);sig.setGravity(Gravity.CENTER);c.addView(sig,new LinearLayout.LayoutParams(dp(52),dp(36)));body.addView(c);gap(5);}
  gap(8);body.addView(t("Piyasa Özeti",15,Color.WHITE,true));gap(5);LinearLayout idx=new LinearLayout(this);String[] ni={"BIST 100\n10.984  +%0,82","DAX\n19.212  +%0,31","S&P 500\n6.742  +%0,46","NASDAQ\n22.518  +%0,55"};for(String q:ni){LinearLayout c=card();c.addView(t(q,9,Color.WHITE,true));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(55),1);lp.setMargins(dp(2),0,dp(2),0);idx.addView(c,lp);}body.addView(idx);gap(12);
  LinearLayout news=card();news.addView(t("SON DAKİKA",9,RED,true));news.addView(t("Piyasalardaki önemli gelişmeler burada gösterilecek.",11,Color.WHITE,true));news.addView(t("Haber ve veri bağlantıları sonraki aşamada bağlanacak.",9,MUTED,false));body.addView(news);
  LinearLayout nav=new LinearLayout(this);nav.setPadding(dp(3),dp(4),dp(3),dp(5));nav.setBackgroundColor(Color.rgb(7,27,46));String[] n={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(n[i],9,i==0?BLUE:MUTED,i==0);v.setGravity(Gravity.CENTER);final int k=i;v.setOnClickListener(x->{if(k==0)showHome();else if(k==1||k==2)showRadar();else if(k==3)showPortfolio();else showMore();});nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showDetail(){ screen=3; syncRadarIndex();
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);
  ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(10));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showRadar());h.addView(back,new LinearLayout.LayoutParams(dp(30),dp(42))); TextView prev=t("‹",20,MUTED,true);prev.setGravity(Gravity.CENTER);prev.setOnClickListener(v->moveRadar(-1));h.addView(prev,new LinearLayout.LayoutParams(dp(28),dp(42)));TextView logo=pill("✈",RED);h.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t(selectedSymbol,16,Color.WHITE,true));nm.addView(t(companyName(selectedTicker),9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));h.addView(t("＋ ★",17,Color.rgb(245,178,43),true),new LinearLayout.LayoutParams(dp(58),dp(42))); TextView next=t("›",20,MUTED,true);next.setGravity(Gravity.CENTER);next.setOnClickListener(v->moveRadar(1));h.addView(next,new LinearLayout.LayoutParams(dp(28),dp(42)));body.addView(h);
  livePrice=t("Veri yükleniyor…",27,Color.WHITE,true);liveChange=t("",14,MUTED,true);liveTime=t("",9,MUTED,false);body.addView(livePrice);body.addView(liveChange);body.addView(liveTime);loadLiveQuote();gap(7);
  LinearLayout tabs=new LinearLayout(this);String[] ts={"Genel","Grafik","Haber","KAP","Finansal"};for(int i=0;i<5;i++){TextView x=t(ts[i],10,i==0?Color.WHITE:MUTED,i==0);x.setGravity(Gravity.CENTER);final int k=i;x.setOnClickListener(v->{if(k==0)showDetail();else if(k==1)showChart();else if(k==2||k==3)showNews();else showFinancial();});tabs.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(tabs);gap(8);
  liveStats=new LinearLayout(this);setLiveStats(null);body.addView(liveStats);gap(8);
  LinearLayout act=new LinearLayout(this);String[] aa={"HIZLI","DENGELİ","TEYİTLİ"};int[] co={GREEN,Color.rgb(238,151,35),BLUE};ShortPulseEngine.Profile[] profiles={ShortPulseEngine.Profile.FAST,ShortPulseEngine.Profile.BALANCED,ShortPulseEngine.Profile.CONFIRMED};for(int i=0;i<3;i++){TextView x=pill(aa[i],profiles[i]==selectedProfile?co[i]:PANEL);final ShortPulseEngine.Profile profile=profiles[i];x.setOnClickListener(v->{selectedProfile=profile;getSharedPreferences("borsaradar",MODE_PRIVATE).edit().putString("selectedProfile",profile.name()).apply();loadComputedSignal();Toast.makeText(this,"Profil: "+profile.name(),Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(44),1);lp.setMargins(dp(3),0,dp(3),0);act.addView(x,lp);}body.addView(act);computedSignal=t("Sinyal hesaplanıyor…",11,MUTED,true);computedSignal.setGravity(Gravity.CENTER);body.addView(computedSignal);horizonSignals=new LinearLayout(this);horizonSignals.setGravity(Gravity.CENTER);body.addView(horizonSignals,new LinearLayout.LayoutParams(-1,dp(58)));loadComputedSignal();gap(13);
  LinearLayout quickHead=new LinearLayout(this);quickHead.setGravity(Gravity.CENTER_VERTICAL);quickHead.addView(t("Hızlı Bilgiler",14,Color.WHITE,true),new LinearLayout.LayoutParams(0,dp(34),1));TextView technical=pill("Teknik Analiz ›",BLUE);technical.setOnClickListener(v->showTechnical());quickHead.addView(technical,new LinearLayout.LayoutParams(dp(115),dp(32)));body.addView(quickHead);gap(5);LinearLayout quick=new LinearLayout(this);String[] q={"F/K\n5,8","PD/DD\n0,9","Temettü Verimi\n%3,2","Beta\n1,1"};for(String s:q){LinearLayout ca=card();TextView x=t(s,10,Color.WHITE,false);x.setGravity(Gravity.CENTER);ca.addView(x);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(62),1);lp.setMargins(dp(2),0,dp(2),0);quick.addView(ca,lp);}body.addView(quick);gap(13);
  body.addView(t("Günlük Aralık",11,Color.WHITE,true));ProgressBar p1=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p1.setMax(100);p1.setProgress(76);body.addView(p1,new LinearLayout.LayoutParams(-1,dp(18)));body.addView(t("272,60                                                       278,40",9,MUTED,false));gap(8);
  body.addView(t("52 Hafta Aralığı",11,Color.WHITE,true));ProgressBar p2=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p2.setMax(100);p2.setProgress(72);body.addView(p2,new LinearLayout.LayoutParams(-1,dp(18)));body.addView(t("193,50                                                       298,75",9,MUTED,false));
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showChart(){ screen=4;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);
  ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(10));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.addView(t("‹",24,Color.WHITE,true),new LinearLayout.LayoutParams(dp(30),dp(42)));TextView logo=pill("✈",RED);h.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t(selectedSymbol,16,Color.WHITE,true));nm.addView(t(companyName(selectedTicker),9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));h.addView(t("＋  ★",18,Color.rgb(245,178,43),true),new LinearLayout.LayoutParams(dp(70),dp(42)));body.addView(h);
  chartPrice=t("Veri yükleniyor…",27,Color.WHITE,true);chartChange=t("",14,MUTED,true);body.addView(chartPrice);body.addView(chartChange);loadChartQuote();gap(6);
  LinearLayout tabs=new LinearLayout(this);String[] ts={"Genel","Grafik","Haber","KAP","Finansal"};for(int i=0;i<5;i++){TextView x=t(ts[i],10,i==1?Color.WHITE:MUTED,i==1);x.setGravity(Gravity.CENTER);final int k=i;x.setOnClickListener(v->{if(k==0)showDetail();else if(k==1)showChart();else if(k==2||k==3)showNews();else if(k==4)showFinancial();});tabs.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(tabs);gap(8);
  LinearLayout tf=new LinearLayout(this);String[] fs={"1G","1H","1A","3A","6A","1Y","2Y"};for(int i=0;i<7;i++){TextView x=t(fs[i],9,i==2?Color.WHITE:MUTED,true);x.setGravity(Gravity.CENTER);x.setBackground(bg(i==2?BLUE:PANEL,8));final String period=fs[i];x.setOnClickListener(v->loadRealChart(period));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(30),1);lp.setMargins(dp(2),0,dp(2),0);tf.addView(x,lp);}body.addView(tf);gap(8);
  LinearLayout chart=card();chart.addView(t("MA(20) 273,40     MA(50) 265,12     MA(200) 238,56",9,MUTED,false));chart.addView(t("       │  ╷     ╻ ╷    ╻\n  278  │  ┃ ╷   ┃ ┃ ╷  ┃\n  274  │╷ ┃ ┃ ╻ ┃ ┃ ┃╻ ┃   277,20\n  270  │┃ ┃ ┃ ┃ ┃ ┃ ┃┃ ┃\n  266  │┃ ╵ ┃ ┃ ╵ ┃ ┃┃ ╵\n       └────────────────────",13,Color.WHITE,false));chart.addView(t("Hacim   ▂ ▅ ▃ ▇ ▄ ▆ ▃ ▅ ▇ ▄ ▆",10,BLUE,true));body.addView(chart,new LinearLayout.LayoutParams(-1,dp(210)));gap(8);
  LinearLayout inds=new LinearLayout(this);String[] ii={"RSI","MACD","Stoch","CCI","BB"};for(String s:ii){TextView x=pill(s,s.equals("RSI")?BLUE:PANEL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(30),1);lp.setMargins(dp(2),0,dp(2),0);inds.addView(x,lp);}body.addView(inds);gap(8);
  LinearLayout rsi=card();rsi.addView(t("RSI (14)                                      62,4",10,Color.WHITE,true));rsi.addView(t("70  ─────────────────────\n          ╱╲      ╱╲\n50  ───╱───╲──╱───╲────\n30  ─────────────────────",11,GREEN,false));body.addView(rsi,new LinearLayout.LayoutParams(-1,dp(105)));
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showNews(){ screen=5;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(10));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.addView(t("‹",24,Color.WHITE,true),new LinearLayout.LayoutParams(dp(30),dp(42)));TextView logo=pill("✈",RED);h.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t(selectedSymbol,16,Color.WHITE,true));nm.addView(t(companyName(selectedTicker),9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));h.addView(t("＋  ★",18,Color.rgb(245,178,43),true),new LinearLayout.LayoutParams(dp(70),dp(42)));body.addView(h);body.addView(t("277,20 ₺",27,Color.WHITE,true));body.addView(t("+4,90  (+1,80%)",14,GREEN,true));gap(6);
  LinearLayout tabs=new LinearLayout(this);String[] ts={"Genel","Grafik","Haber","KAP","Finansal"};for(int i=0;i<5;i++){TextView x=t(ts[i],10,i==2?Color.WHITE:MUTED,i==2);x.setGravity(Gravity.CENTER);final int k=i;x.setOnClickListener(v->{if(k==0)showDetail();else if(k==1)showChart();else if(k==2||k==3)showNews();else if(k==4)showFinancial();});tabs.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(tabs);gap(8);
  LinearLayout filters=new LinearLayout(this);String[] fs={"Tümü","KAP","Medya","Analist"};for(int i=0;i<4;i++){TextView x=pill(fs[i],i==0?BLUE:PANEL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(30),1);lp.setMargins(dp(2),0,dp(2),0);filters.addView(x,lp);}body.addView(filters);gap(8);
  String[][] n={{"14:21","THYAO, Airbus ile 150 uçak için niyet mektubu imzaladı","Bloomberg","Pozitif"},{"12:10","THY’den yeni hat açıklaması: Sydney seferleri başlıyor","AA","Pozitif"},{"10:45","Analistler THYAO hedef fiyatlarını yükseltti","İş Yatırım","Pozitif"},{"09:32","THYAO 2. çeyrek yolcu verileri açıklandı","KAP","Nötr"},{"Dün 18:20","Uluslararası havayolları hisselerinde genel yükseliş","Reuters","Pozitif"}};for(String[] q:n){LinearLayout ca=card();ca.addView(t(q[0]+"   "+q[2],9,MUTED,false));ca.addView(t(q[1],11,Color.WHITE,true));ca.addView(t(q[3],9,q[3].equals("Pozitif")?GREEN:Color.rgb(239,177,57),true));body.addView(ca);gap(6);}
  TextView all=t("Tüm Haberleri Gör",11,Color.WHITE,true);all.setOnClickListener(v->Toast.makeText(this,"Tüm "+selectedTicker+" haberleri",Toast.LENGTH_SHORT).show());all.setGravity(Gravity.CENTER);all.setBackground(bg(BLUE,10));body.addView(all,new LinearLayout.LayoutParams(-1,dp(42)));
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showFinancial(){ screen=6;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(10));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showHome());h.addView(back,new LinearLayout.LayoutParams(dp(30),dp(42)));TextView logo=pill("✈",RED);h.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t(selectedSymbol,16,Color.WHITE,true));nm.addView(t(companyName(selectedTicker),9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));body.addView(h);body.addView(t("277,20 ₺",27,Color.WHITE,true));body.addView(t("+4,90  (+1,80%)",14,GREEN,true));gap(6);
  LinearLayout tabs=new LinearLayout(this);String[] ts={"Genel","Grafik","Haber","KAP","Finansal"};for(int i=0;i<5;i++){TextView x=t(ts[i],10,i==4?Color.WHITE:MUTED,i==4);x.setGravity(Gravity.CENTER);final int k=i;x.setOnClickListener(v->{if(k==0)showDetail();else if(k==1)showChart();else if(k==2||k==3)showNews();else showFinancial();});tabs.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(tabs);gap(8);
  LinearLayout sub=new LinearLayout(this);String[] st={"Özet","Gelir Tablosu","Bilanço","Nakit Akışı"};for(int i=0;i<4;i++){TextView x=pill(st[i],i==0?BLUE:PANEL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(30),1);lp.setMargins(dp(2),0,dp(2),0);sub.addView(x,lp);}body.addView(sub);gap(10);body.addView(t("Temel Finansal Veriler (Son 12 Ay)",14,Color.WHITE,true));gap(5);
  String[][] rows={{"Piyasa Değeri","382,1 Mr ₺"},{"F/K","5,8"},{"PD/DD","0,9"},{"FD/FAVÖK","4,1"},{"Hisse Başına Kar","47,8 ₺"},{"Temettü Verimi","%3,2"},{"Özkaynak Karlılığı","%15,4"},{"Net Kar (Son Çeyrek)","22,4 Mr ₺"},{"Gelir (Son Çeyrek)","176,3 Mr ₺"},{"Yıllık Gelir Büyümesi","%32,1"},{"Yıllık Kar Büyümesi","%48,7"},{"Sektör","Ulaştırma"},{"52 Hafta En Düşük","193,50 ₺"},{"52 Hafta En Yüksek","298,75 ₺"}};for(String[] q:rows){if("AL Sinyali".equals(radarFilter)&&!"AL".equals(q[3]))continue;if("İzle".equals(radarFilter)&&!"İZLE".equals(q[3]))continue;if("SAT".equals(radarFilter)&&!"SAT".equals(q[3]))continue;LinearLayout row=new LinearLayout(this);row.setPadding(dp(8),dp(7),dp(8),dp(7));row.setBackground(bg(PANEL,7));row.addView(t(q[0],10,MUTED,false),new LinearLayout.LayoutParams(0,dp(26),1));TextView val=t(q[1],10,Color.WHITE,true);val.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);row.addView(val,new LinearLayout.LayoutParams(dp(130),dp(26)));body.addView(row);gap(2);}
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);if(i==0)v.setOnClickListener(x->showHome());nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showRadar(){ screen=2; selectedSymbol=lastRadarSymbol;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(8));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showHome());h.addView(back,new LinearLayout.LayoutParams(dp(34),dp(42)));h.addView(t("Radar Taraması",18,Color.WHITE,true),new LinearLayout.LayoutParams(0,dp(42),1));h.addView(t("⌕",22,Color.WHITE,false),new LinearLayout.LayoutParams(dp(34),dp(42)));body.addView(h);gap(6);
  LinearLayout filters=new LinearLayout(this);String[] fs={"Tümü","AL Sinyali","İzle","SAT"};for(int i=0;i<fs.length;i++){final String filter=fs[i];TextView x=pill(fs[i],fs[i].equals(radarFilter)?BLUE:PANEL);x.setOnClickListener(v->{radarFilter=filter;renderRadarRows(cachedRadarRows);});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(32),1);lp.setMargins(dp(2),0,dp(2),0);filters.addView(x,lp);}body.addView(filters);gap(8);TextView scanState=t(scanDone?"Son tarama korunuyor • "+scanMode:"Henüz tarama yapılmadı",9,scanDone?GREEN:MUTED,true);body.addView(scanState);radarProgress=t("",9,BLUE,true);body.addView(radarProgress);gap(5);
  LinearLayout drops=new LinearLayout(this);String[] ds={selectedMarket+" ▾","Tüm Sektörler ▾","Teknik + Temel ▾"};for(String s:ds){TextView x=pill(s,PANEL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(34),1);lp.setMargins(dp(2),0,dp(2),0);drops.addView(x,lp);}body.addView(drops);gap(10);
  LinearLayout head=new LinearLayout(this);String[] hc={"Kod","Son Fiyat","Değişim","Sinyal"};for(String s:hc){TextView x=t(s,9,MUTED,true);x.setGravity(Gravity.CENTER);head.addView(x,new LinearLayout.LayoutParams(0,dp(28),1));}body.addView(head);
  radarRows=new LinearLayout(this);radarRows.setOrientation(LinearLayout.VERTICAL);body.addView(radarRows);if(!cachedRadarRows.isEmpty())renderRadarRows(cachedRadarRows);else if(scanDone){renderRadarLoading();loadRadarRows();}else radarRows.addView(t("Tarama için Stratejiler > Taramayı Başlat",11,MUTED,true));
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,i==2?BLUE:MUTED,i==2);v.setGravity(Gravity.CENTER);final int k=i;if(k==0)v.setOnClickListener(x->showHome());else if(k==2)v.setOnClickListener(x->showRadar());nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showTechnical(){ screen=7;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(8));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showDetail());h.addView(back,new LinearLayout.LayoutParams(dp(30),dp(42)));h.addView(pill("✈",RED),new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t(selectedSymbol,16,Color.WHITE,true));nm.addView(t(companyName(selectedTicker),9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));body.addView(h);body.addView(t("277,20 ₺",27,Color.WHITE,true));body.addView(t("+4,90  (+1,80%)",14,GREEN,true));gap(8);
  LinearLayout techTitle=new LinearLayout(this);techTitle.setGravity(Gravity.CENTER_VERTICAL);techTitle.addView(t("İndikatör Sinyalleri",15,Color.WHITE,true),new LinearLayout.LayoutParams(0,dp(34),1));TextView target=pill("Hedef & Risk ›",BLUE);target.setOnClickListener(v->showTargetRisk());techTitle.addView(target,new LinearLayout.LayoutParams(dp(110),dp(32)));body.addView(techTitle);gap(5);LinearLayout hd=new LinearLayout(this);String[] hh={"İndikatör","Değer","Sinyal"};for(String s:hh){TextView x=t(s,9,MUTED,true);x.setGravity(Gravity.CENTER);hd.addView(x,new LinearLayout.LayoutParams(0,dp(28),1));}body.addView(hd);
  String[][] rows={{"RSI(14)","62,4","İZLE"},{"MACD","2,14","AL"},{"Stochastic","78,1","TUT"},{"CCI","123,4","AL"},{"EMA20","270,2","AL"},{"EMA50","265,8","AL"},{"EMA200","238,6","AL"},{"Bollinger (BB)","Üst Banda Yakın","İZLE"},{"ATR","4,21","-"},{"SuperTrend","","AL"},{"Fibonacci","274,0 (0)","Destek"}};
  for(String[] q:rows){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(3),dp(3),dp(3),dp(3));TextView a=t(q[0],10,Color.WHITE,true),b=t(q[1],9,MUTED,false),d=pill(q[2],q[2].equals("AL")?GREEN:q[2].equals("TUT")||q[2].equals("İZLE")?AMBER:PANEL);a.setGravity(Gravity.CENTER);b.setGravity(Gravity.CENTER);row.addView(a,new LinearLayout.LayoutParams(0,dp(32),1));row.addView(b,new LinearLayout.LayoutParams(0,dp(32),1));row.addView(d,new LinearLayout.LayoutParams(0,dp(32),1));body.addView(row);}
  gap(8);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(10),dp(12),dp(10));card.setBackground(bg(PANEL,10));card.addView(t("Genel Teknik Görünüm",14,Color.WHITE,true));TextView al=t("AL",30,GREEN,true);al.setGravity(Gravity.CENTER);card.addView(al);TextView power=t("Alım Gücü  %72",14,Color.WHITE,true);power.setGravity(Gravity.CENTER);card.addView(power);gap(4);LinearLayout horizons=new LinearLayout(this);String[][] hs={{"Kısa Vade","AL"},{"Orta Vade","AL"},{"Uzun Vade","TUT"}};for(String[] q:hs){LinearLayout z=new LinearLayout(this);z.setOrientation(LinearLayout.VERTICAL);TextView q1=t(q[0],9,MUTED,false),q2=t(q[1],12,q[1].equals("AL")?GREEN:AMBER,true);q1.setGravity(Gravity.CENTER);q2.setGravity(Gravity.CENTER);z.addView(q1);z.addView(q2);horizons.addView(z,new LinearLayout.LayoutParams(0,dp(48),1));}card.addView(horizons);body.addView(card);
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);final int k=i;if(k==0)v.setOnClickListener(x->showHome());else if(k==2)v.setOnClickListener(x->showRadar());nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showTargetRisk(){ screen=8;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(8));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showDetail());h.addView(back,new LinearLayout.LayoutParams(dp(30),dp(42)));h.addView(pill("✈",RED),new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t(selectedSymbol,16,Color.WHITE,true));nm.addView(t(companyName(selectedTicker),9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));body.addView(h);body.addView(t("277,20 ₺",27,Color.WHITE,true));body.addView(t("+4,90  (+1,80%)",14,GREEN,true));gap(8);
  body.addView(t("Analist Hedef & Tahminleri",15,Color.WHITE,true));gap(5);
  String[][] targets={{"Ortalama Hedef","323,50 ₺","+18,5%"},{"En Yüksek Hedef","380,00 ₺","+37,1%"},{"En Düşük Hedef","290,00 ₺","+4,6%"},{"Analist Sayısı","15",""}};
  for(String[] q:targets){LinearLayout row=new LinearLayout(this);row.setPadding(dp(9),dp(7),dp(9),dp(7));row.setBackground(bg(PANEL,8));row.addView(t(q[0],10,MUTED,false),new LinearLayout.LayoutParams(0,dp(28),1));TextView v=t(q[1],11,Color.WHITE,true);v.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);row.addView(v,new LinearLayout.LayoutParams(dp(100),dp(28)));TextView ch=t(q[2],10,GREEN,true);ch.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);row.addView(ch,new LinearLayout.LayoutParams(dp(65),dp(28)));body.addView(row);gap(2);}
  gap(8);LinearLayout hs=new LinearLayout(this);String[][] horizons={{"Kısa Vade\n1-3 Ay","295,00 ₺\n+6,4%"},{"Orta Vade\n3-12 Ay","321,50 ₺\n+16,5%"},{"Uzun Vade\n1-2 Yıl","360,00 ₺\n+29,9%"}};for(String[] q:horizons){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setGravity(Gravity.CENTER);card.setBackground(bg(PANEL,9));TextView a=t(q[0],9,MUTED,true),b=t(q[1],11,GREEN,true);a.setGravity(Gravity.CENTER);b.setGravity(Gravity.CENTER);card.addView(a);card.addView(b);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(82),1);lp.setMargins(dp(2),0,dp(2),0);hs.addView(card,lp);}body.addView(hs);
  gap(10);body.addView(t("Destek / Direnç",14,Color.WHITE,true));String[][] levels={{"Direnç 2","298,75 ₺"},{"Direnç 1","285,00 ₺"},{"Güncel Fiyat","277,20 ₺"},{"Destek 1","272,00 ₺"},{"Destek 2","260,00 ₺"}};for(String[] q:levels){LinearLayout row=new LinearLayout(this);row.addView(t(q[0],10,MUTED,false),new LinearLayout.LayoutParams(0,dp(30),1));TextView v=t(q[1],10,q[0].startsWith("Direnç")?RED:q[0].startsWith("Destek")?GREEN:Color.WHITE,true);v.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);row.addView(v,new LinearLayout.LayoutParams(dp(120),dp(30)));body.addView(row);}
  gap(8);body.addView(t("Risk Yönetimi",14,Color.WHITE,true));LinearLayout risk=new LinearLayout(this);risk.setOrientation(LinearLayout.VERTICAL);risk.setPadding(dp(10),dp(8),dp(10),dp(8));risk.setBackground(bg(PANEL,9));risk.addView(t("Zarar Durdur     260,00 ₺   (-6,2%)",11,RED,true));risk.addView(t("Olası Getiri/Risk Oranı     2,8",11,Color.WHITE,true));body.addView(risk);
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);final int k=i;if(k==0)v.setOnClickListener(x->showHome());else if(k==2)v.setOnClickListener(x->showRadar());nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showPortfolio(){ screen=9;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(8));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showHome());h.addView(back,new LinearLayout.LayoutParams(dp(34),dp(42)));h.addView(t("Portföyüm",18,Color.WHITE,true),new LinearLayout.LayoutParams(0,dp(42),1));h.addView(t("⋮",22,Color.WHITE,true),new LinearLayout.LayoutParams(dp(34),dp(42)));body.addView(h);
  gap(4);body.addView(t("Toplam Değer",10,MUTED,false));body.addView(t("482.650 ₺",28,Color.WHITE,true));body.addView(t("+12.340 ₺  (+2,62%)  Bugün",12,GREEN,true));gap(8);
  LinearLayout tabs=new LinearLayout(this);TextView p1=pill("Portföy",BLUE),p2=pill("İşlemler",PANEL);tabs.addView(p1,new LinearLayout.LayoutParams(0,dp(34),1));tabs.addView(p2,new LinearLayout.LayoutParams(0,dp(34),1));body.addView(tabs);gap(8);
  LinearLayout hd=new LinearLayout(this);String[] hh={"Hisse","Adet","Ort. Maliyet","Güncel","K/Z"};for(String s:hh){TextView x=t(s,8,MUTED,true);x.setGravity(Gravity.CENTER);hd.addView(x,new LinearLayout.LayoutParams(0,dp(28),1));}body.addView(hd);
  String[][] rows={{"THYAO","500","220,50","277,20","+%25,7"},{"BIMAS","200","260,10","287,50","+%10,5"},{"TCELL","1.000","65,30","71,24","+%9,1"},{"PETKM","2.000","19,80","20,08","+%1,4"},{"NVDA","10","150,20","177,26","+%18,0"}};
  for(String[] q:rows){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(2),dp(3),dp(2),dp(3));for(int i=0;i<5;i++){TextView x=t(q[i],9,i==4?GREEN:Color.WHITE,i==0);x.setGravity(Gravity.CENTER);if(i==0)x.setOnClickListener(v->{selectedSymbol=q[0];showDetail();});row.addView(x,new LinearLayout.LayoutParams(0,dp(38),1));}body.addView(row);}
  gap(6);LinearLayout total=new LinearLayout(this);total.setPadding(dp(8),dp(8),dp(8),dp(8));total.setBackground(bg(PANEL,8));total.addView(t("Toplam K/Z",11,MUTED,true),new LinearLayout.LayoutParams(0,dp(30),1));TextView tv=t("+73.850 ₺  (+18,0%)",12,GREEN,true);tv.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);total.addView(tv,new LinearLayout.LayoutParams(dp(180),dp(30)));body.addView(total);gap(10);
  LinearLayout acts=new LinearLayout(this);TextView add=pill("+ Hisse Ekle",BLUE);TextView analyze=pill("Portföy Analiz",PANEL);add.setOnClickListener(v->showAddStockDialog());analyze.setOnClickListener(v->showTechnical());LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(0,dp(42),1);ap.setMargins(dp(2),0,dp(2),0);acts.addView(add,ap);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(42),1);bp.setMargins(dp(2),0,dp(2),0);acts.addView(analyze,bp);body.addView(acts);
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,i==3?BLUE:MUTED,i==3);v.setGravity(Gravity.CENTER);final int k=i;if(k==0)v.setOnClickListener(x->showHome());else if(k==2)v.setOnClickListener(x->showRadar());else if(k==3)v.setOnClickListener(x->showPortfolio());nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showStrategy(){ screen=10;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(8));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showHome());h.addView(back,new LinearLayout.LayoutParams(dp(34),dp(42)));h.addView(t("Strateji Seç",18,Color.WHITE,true),new LinearLayout.LayoutParams(0,dp(42),1));body.addView(h);gap(8);
  String[][] cards={{"⚡  Kısa Vade","Günlük ve saatlik fırsatları teknik sinyallerle tara."},{"◆  Temettü","Düzenli temettü ve finansal güç potansiyelini değerlendir."},{"↗  Uzun Vade","Temel değerleme ve uzun vadeli büyüme fırsatlarını tara."}};int[] cc={GREEN,BLUE,Color.rgb(128,86,210)};for(int i=0;i<cards.length;i++){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(12),dp(14),dp(12));card.setBackground(bg(cc[i],10));card.addView(t(cards[i][0],15,Color.WHITE,true));card.addView(t(cards[i][1],10,Color.WHITE,false));body.addView(card,new LinearLayout.LayoutParams(-1,dp(76)));gap(7);}
  gap(5);body.addView(t("Tarama Kriterleri",14,Color.WHITE,true));String[] criteria={"Teknik Analiz","Temel Analiz","Haber Taraması","Sektör Analizi","Büyük Alıcı/Satıcı","Finansal Güç","Temettü Potansiyeli"};for(String s:criteria){android.widget.CheckBox cb=new android.widget.CheckBox(this);cb.setText(s);cb.setTextColor(Color.WHITE);cb.setTextSize(11);cb.setChecked(true);cb.setButtonTintList(android.content.res.ColorStateList.valueOf(BLUE));body.addView(cb,new LinearLayout.LayoutParams(-1,dp(38)));}
  gap(8);TextView start=pill("Taramayı Başlat",GREEN);start.setTextSize(13);start.setOnClickListener(v->{scanDone=true;scanMode="Teknik + Temel";cachedRadarRows.clear();getSharedPreferences("borsaradar",MODE_PRIVATE).edit().putBoolean("scanDone",true).putString("scanMode",scanMode).apply();showRadar();});body.addView(start,new LinearLayout.LayoutParams(-1,dp(48)));
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);final int k=i;if(k==0)v.setOnClickListener(x->showHome());else if(k==2)v.setOnClickListener(x->showRadar());else if(k==3)v.setOnClickListener(x->showPortfolio());nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showMore(){ screen=11;
  LinearLayout root=detailRoot();body.addView(t("Diğer",20,Color.WHITE,true));gap(8);LinearLayout profile=card();profile.addView(t("EK   Erdogan Kulanoglu",15,Color.WHITE,true));profile.addView(t("Pro Hesap",10,BLUE,true));body.addView(profile);gap(8);
  String[] items={"Piyasa Takvimi","Sektörler","Favorilerim","Alarmlar","Hisse Karşılaştırma","Döviz / Altın / Emtia","Ekonomik Veriler","Ayarlar","Yardım & Destek","Hakkında"};for(String s:items){TextView v=t(s+"   ›",12,Color.WHITE,false);v.setPadding(dp(12),0,dp(12),0);v.setBackground(bg(PANEL,8));v.setOnClickListener(x->Toast.makeText(this,s+" açılacak",Toast.LENGTH_SHORT).show());body.addView(v,new LinearLayout.LayoutParams(-1,dp(42)));gap(3);}TextView out=pill("Çıkış Yap",RED);body.addView(out,new LinearLayout.LayoutParams(-1,dp(42)));nav(root,4);setContentView(root);
 }

 private void renderRadarLoading(){if(radarRows==null)return;radarRows.removeAllViews();for(String s:radarSymbols){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);String[] a={s,"…","…","…"};for(int i=0;i<4;i++){TextView x=t(a[i],10,i==0?Color.WHITE:MUTED,i==0);x.setGravity(Gravity.CENTER);row.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}radarRows.addView(row);}}
 private String[] analyzeRadarSymbol(String s){try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(s,"6mo","1d",180);if(d==null||d.size()<35)return null;int n=d.size(),end=n-1;double price=d.get(end).close,prev=d.get(end-1).close,ma20=0,g=0,l=0,hi=-Double.MAX_VALUE,lo=Double.MAX_VALUE,tp=0,md=0;MarketDataService.Spot sp=MarketDataService.latestSpot(s);if(sp!=null&&sp.price>0)price=sp.price;for(int i=n-20;i<n;i++)ma20+=d.get(i).close;ma20/=20d;for(int i=n-14;i<n;i++){MarketDataService.Candle x=d.get(i);double z=x.close-d.get(i-1).close;if(z>=0)g+=z;else l-=z;hi=Math.max(hi,x.high);lo=Math.min(lo,x.low);tp+=(x.high+x.low+x.close)/3d;}double rsi=100-(100/(1+(l==0?100:g/l))),stoch=hi==lo?50:100*(price-lo)/(hi-lo),mtp=tp/14d;for(int i=n-14;i<n;i++){MarketDataService.Candle x=d.get(i);md+=Math.abs((x.high+x.low+x.close)/3d-mtp);}md/=14d;double cci=md==0?0:(((d.get(end).high+d.get(end).low+price)/3d)-mtp)/(0.015d*md),macd=ema(d,12,end)-ema(d,26,end),macdPrev=ema(d,12,end-1)-ema(d,26,end-1);int score=0;score+=price>ma20?1:-1;if(rsi<35)score++;else if(rsi>70)score--;if(macd>0&&macd>=macdPrev)score++;else if(macd<0&&macd<=macdPrev)score--;if(stoch<25)score++;else if(stoch>80)score--;if(cci>100)score++;else if(cci<-100)score--;int shortScore=score;double ma50=ema(d,50,end),ma100=ema(d,Math.min(100,n),end);int mediumScore=(price>ma20?1:-1)+(ma20>ma50?1:-1)+(macd>0?1:-1);int longScore=(price>ma50?1:-1)+(ma50>ma100?1:-1)+(cci>0?1:-1);String sig=score>=2?"AL":score<=-2?"SAT":"İZLE";String shortSig=shortScore>=2?"AL":shortScore<=-2?"SAT":"İZLE",mediumSig=mediumScore>=2?"AL":mediumScore<=-2?"SAT":"İZLE",longSig=longScore>=2?"AL":longScore<=-2?"SAT":"İZLE";int confidence=Math.min(95,50+Math.abs(score)*9);double pct=prev==0?0:(price-prev)/prev*100d;return new String[]{s,String.format(java.util.Locale.GERMANY,"%.2f",price),String.format(java.util.Locale.GERMANY,"%+.2f%%",pct),sig,String.valueOf(score),String.format(java.util.Locale.GERMANY,"Güven %d%% • Kısa %s • Orta %s • Uzun %s\nRSI %.0f • MACD %.2f • Stoch %.0f • CCI %.0f",confidence,shortSig,mediumSig,longSig,rsi,macd,stoch,cci),String.valueOf(confidence),shortSig,mediumSig,longSig};}catch(Exception ex){return null;}}
 private void loadRadarRows(){if(radarLoading)return;radarLoading=true;final String[] symbols=radarUniverse().clone();final java.util.concurrent.ExecutorService pool=java.util.concurrent.Executors.newFixedThreadPool(6);final java.util.concurrent.ConcurrentLinkedQueue<String[]> out=new java.util.concurrent.ConcurrentLinkedQueue<>();final java.util.concurrent.atomic.AtomicInteger done=new java.util.concurrent.atomic.AtomicInteger();for(String sym:symbols){pool.execute(()->{String[] row=analyzeRadarSymbol(sym);if(row!=null)out.add(row);int x=done.incrementAndGet();runOnUiThread(()->{if(radarProgress!=null&&screen==2)radarProgress.setText("Tarama: "+x+"/"+symbols.length+"  %"+Math.round(x*100f/symbols.length));});if(x==symbols.length){pool.shutdown();final java.util.ArrayList<String[]> result=new java.util.ArrayList<>(out);java.util.Collections.sort(result,(a,b)->Integer.compare(Integer.parseInt(b[4]),Integer.parseInt(a[4])));runOnUiThread(()->{radarLoading=false;cachedRadarRows.clear();cachedRadarRows.addAll(result);radarCacheByMarket.put(selectedMarket,new java.util.ArrayList<>(result));scanDone=true;scanDoneByMarket.put(selectedMarket,true);getSharedPreferences("borsaradar",MODE_PRIVATE).edit().putBoolean("scanDone_"+selectedMarket,true).apply();if(radarProgress!=null)radarProgress.setText("Tarama tamamlandı • "+result.size()+" hisse");renderRadarRows(cachedRadarRows);});}});}}
 private void renderRadarRows(java.util.List<String[]> rows){if(radarRows==null||screen!=2)return;radarRows.removeAllViews();for(String[] q:rows){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(2),dp(3),dp(2),dp(3));for(int i=0;i<4;i++){int col=i==2?(q[i].startsWith("-")?RED:GREEN):Color.WHITE;TextView x=i==3?pill(q[i]+(q.length>6?" "+q[6]+"%":""),q[i].equals("AL")?GREEN:q[i].equals("SAT")?RED:AMBER):t(q[i],10,col,i==0);x.setGravity(Gravity.CENTER);final String sym=q[0];if(i==0){x.setOnLongClickListener(v->{Toast.makeText(this,q.length>5?q[5]:"",Toast.LENGTH_LONG).show();return true;});x.setOnClickListener(v->{selectedSymbol=sym;lastRadarSymbol=sym;getSharedPreferences("borsaradar",MODE_PRIVATE).edit().putString("lastRadarSymbol",sym).apply();showDetail();});}row.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}radarRows.addView(row);}if(rows.isEmpty())radarRows.addView(t("Radar verisi alınamadı",11,RED,true));}
 private void loadLiveQuote(){ final String symbol=selectedSymbol; uiIo.execute(()->{try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(symbol,"5d","5m",400);if(d==null||d.size()<2)return;MarketDataService.Candle last=d.get(d.size()-1),prev=d.get(d.size()-2);double spot=last.close;MarketDataService.Spot sp=MarketDataService.latestSpot(symbol);if(sp!=null&&sp.price>0)spot=sp.price;double hi=last.high,lo=last.low,vol=last.volume; for(int i=Math.max(0,d.size()-80);i<d.size();i++){MarketDataService.Candle x=d.get(i);hi=Math.max(hi,x.high);lo=Math.min(lo,x.low);vol+=i==d.size()-1?0:x.volume;} final double price=spot,base=prev.close,chg=price-base,pct=base==0?0:(chg/base*100.0),open=last.open,high=hi,low=lo,volume=vol;final long tm=last.time;runOnUiThread(()->{if(!symbol.equals(selectedSymbol)||livePrice==null)return;livePrice.setText(String.format(java.util.Locale.GERMANY,"%.2f%s",price,currency(symbol)));liveChange.setText(String.format(java.util.Locale.GERMANY,"%+.2f  (%+.2f%%)",chg,pct));liveChange.setTextColor(chg>=0?GREEN:RED);liveTime.setText(new java.text.SimpleDateFormat("dd.MM.yyyy HH:mm",java.util.Locale.GERMANY).format(new java.util.Date(tm*1000L))+" • "+MarketDataService.sourceFor(symbol,"5d","5m"));setLiveStats(new double[]{open,high,low,volume});});}catch(Exception e){runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&livePrice!=null)livePrice.setText("Fiyat alınamadı");});}});}
 private double ema(java.util.List<MarketDataService.Candle>d,int p,int end){double k=2d/(p+1d),e=d.get(Math.max(0,end-p+1)).close;for(int i=Math.max(0,end-p+2);i<=end;i++)e=d.get(i).close*k+e*(1-k);return e;}
 private void loadComputedSignal(){final String symbol=selectedSymbol;uiIo.execute(()->{try{
  java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(symbol,"6mo","1d",180);
  if(d==null||d.size()<35)return;
  ShortPulseEngine.Result p=ShortPulseEngine.analyze(d,symbol,selectedProfile);
  final String sig=p.recommendation.contains("SAT")?"SAT":p.recommendation.contains("AL")?"AL":"TUT";
  final String text=String.format(java.util.Locale.GERMANY,
    "Model: %s • Pulse %.1f • Güven %.0f%%\nBRTV %.1f • BRM %.2f • BRH %.1f\n%s",
    p.recommendation,p.score,p.confidence,p.brtv,p.brm,p.brh,p.phaseText);
  runOnUiThread(()->{if(!symbol.equals(selectedSymbol)||computedSignal==null)return;
    computedSignal.setText(text);computedSignal.setTextColor("AL".equals(sig)?GREEN:"SAT".equals(sig)?RED:AMBER);
  });
 }catch(Exception e){runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&computedSignal!=null)computedSignal.setText("Sinyal hesaplanamadı");});}});}
 private void renderHorizonSignals(String shortSig,String mediumSig,String longSig){if(horizonSignals==null)return;horizonSignals.removeAllViews();String[][] a={{"Kısa",shortSig},{"Orta",mediumSig},{"Uzun",longSig}};for(String[] q:a){LinearLayout z=card();z.setGravity(Gravity.CENTER);TextView h=t(q[0],9,MUTED,true),v=t(q[1],12,"AL".equals(q[1])?GREEN:"SAT".equals(q[1])?RED:AMBER,true);h.setGravity(Gravity.CENTER);v.setGravity(Gravity.CENTER);z.addView(h);z.addView(v);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(54),1);lp.setMargins(dp(2),dp(2),dp(2),dp(2));horizonSignals.addView(z,lp);}}
 private void loadChartQuote(){final String symbol=selectedSymbol;uiIo.execute(()->{try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(symbol,"5d","5m",400);if(d==null||d.size()<2)return;MarketDataService.Candle last=d.get(d.size()-1),prev=d.get(d.size()-2);double spot=last.close;MarketDataService.Spot sp=MarketDataService.latestSpot(symbol);if(sp!=null&&sp.price>0)spot=sp.price;final double price=spot,chg=spot-prev.close,pct=prev.close==0?0:(chg/prev.close*100d);runOnUiThread(()->{if(!symbol.equals(selectedSymbol)||chartPrice==null)return;chartPrice.setText(String.format(java.util.Locale.GERMANY,"%.2f%s",price,currency(symbol)));chartChange.setText(String.format(java.util.Locale.GERMANY,"%+.2f  (%+.2f%%)",chg,pct));chartChange.setTextColor(chg>=0?GREEN:RED);});}catch(Exception e){runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&chartPrice!=null)chartPrice.setText("Fiyat alınamadı");});}});}
 private void setLiveStats(double[] v){if(liveStats==null)return;liveStats.removeAllViews();String[] ss;if(v==null)ss=new String[]{"Açılış\n—","Yüksek\n—","Düşük\n—","Hacim\n—"};else ss=new String[]{String.format(java.util.Locale.GERMANY,"Açılış\n%.2f",v[0]),String.format(java.util.Locale.GERMANY,"Yüksek\n%.2f",v[1]),String.format(java.util.Locale.GERMANY,"Düşük\n%.2f",v[2]),"Hacim\n"+formatVolume(v[3])};for(String s:ss){TextView x=t(s,9,Color.WHITE,false);x.setGravity(Gravity.CENTER);liveStats.addView(x,new LinearLayout.LayoutParams(0,dp(48),1));}}
 private String formatVolume(double v){if(v>=1000000000)return String.format(java.util.Locale.GERMANY,"%.1f Mr",v/1000000000d);if(v>=1000000)return String.format(java.util.Locale.GERMANY,"%.1f M",v/1000000d);if(v>=1000)return String.format(java.util.Locale.GERMANY,"%.1f B",v/1000d);return String.format(java.util.Locale.GERMANY,"%.0f",v);}
 private void syncRadarIndex(){for(int i=0;i<radarSymbols.length;i++)if(radarSymbols[i].equals(selectedSymbol)){radarIndex=i;return;}}
 private void moveRadar(int delta){syncRadarIndex();radarIndex=(radarIndex+delta+radarSymbols.length)%radarSymbols.length;selectedSymbol=radarSymbols[radarIndex];lastRadarSymbol=selectedSymbol;getSharedPreferences("borsaradar",MODE_PRIVATE).edit().putString("lastRadarSymbol",selectedSymbol).apply();showDetail();}

 private void showAddStockDialog(){
  LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),dp(8),dp(20),0);
  EditText ticker=new EditText(this);ticker.setHint("Hisse kodu (örn. THYAO)");EditText qty=new EditText(this);qty.setHint("Adet");qty.setInputType(2);EditText cost=new EditText(this);cost.setHint("Alış fiyatı");cost.setInputType(8194);box.addView(ticker);box.addView(qty);box.addView(cost);
  new android.app.AlertDialog.Builder(this).setTitle("Portföye Hisse Ekle").setView(box).setNegativeButton("İptal",null).setPositiveButton("Ekle",(d,w)->{String s=ticker.getText().toString().trim().toUpperCase();if(s.length()==0)Toast.makeText(this,"Hisse kodu gerekli",Toast.LENGTH_SHORT).show();else Toast.makeText(this,s+" portföye eklendi",Toast.LENGTH_SHORT).show();}).show();
 }

 private void loadRealChart(String period){
  final String[] range={"1d"},interval={"5m"};if("1H".equals(period)){range[0]="5d";interval[0]="5m";}else if("1A".equals(period)){range[0]="1mo";interval[0]="1d";}else if("3A".equals(period)){range[0]="3mo";interval[0]="1d";}else if("6A".equals(period)){range[0]="6mo";interval[0]="1d";}else if("1Y".equals(period)){range[0]="1y";interval[0]="1d";}else if("2Y".equals(period)){range[0]="2y";interval[0]="1d";}
  Toast.makeText(this,period+" verisi yükleniyor",Toast.LENGTH_SHORT).show();uiIo.execute(()->{try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(selectedSymbol,range[0],interval[0],180);runOnUiThread(()->showLiveChart(period,d));}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Grafik verisi alınamadı",Toast.LENGTH_SHORT).show());}});
 }
 private void showLiveChart(String period,java.util.List<MarketDataService.Candle>d){
  if(d==null||d.size()<2)return;LinearLayout root=detailRoot();LinearLayout h=new LinearLayout(this);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showChart());h.addView(back,new LinearLayout.LayoutParams(dp(32),dp(42)));h.addView(t(selectedSymbol+" • "+period,17,Color.WHITE,true),new LinearLayout.LayoutParams(0,dp(42),1));body.addView(h);PriceChartView chart=new PriceChartView(this,d,period);body.addView(chart,new LinearLayout.LayoutParams(-1,dp(430)));TextView tech=pill("Teknik Analiz",BLUE);tech.setOnClickListener(v->showTechnical());body.addView(tech,new LinearLayout.LayoutParams(-1,dp(44)));nav(root,0);setContentView(root);
 }
 private String companyName(String s){if("BIMAS".equals(s))return "BİM Birleşik Mağazalar A.Ş.";if("TCELL".equals(s))return "Turkcell İletişim Hizmetleri A.Ş.";if("ASELS".equals(s))return "ASELSAN Elektronik Sanayi ve Ticaret A.Ş.";if("KRDMD".equals(s))return "Kardemir D";if("PETKM".equals(s))return "Petkim Petrokimya Holding A.Ş.";if("KCHOL".equals(s))return "Koç Holding A.Ş.";if("TUPRS".equals(s))return "Tüpraş";if("GARAN".equals(s))return "Garanti BBVA";if("AKBNK".equals(s))return "Akbank";if("YKBNK".equals(s))return "Yapı Kredi";if("SASA".equals(s))return "SASA Polyester";if("NVDA".equals(s))return "NVIDIA Corporation";return "Türk Hava Yolları A.Ş.";}\n}
