package com.kulanoglu.borsaradar;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.Typeface;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.*;

public class ReferenceUiActivity extends Activity {
 private final int NAVY=Color.rgb(5,18,34), PANEL=Color.rgb(12,34,59), BLUE=Color.rgb(36,118,255), MUTED=Color.rgb(137,163,188), GREEN=Color.rgb(31,191,126), RED=Color.rgb(238,82,83);
 private LinearLayout body; private int screen=0;
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 private android.graphics.drawable.GradientDrawable bg(int c,int r){android.graphics.drawable.GradientDrawable g=new android.graphics.drawable.GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 private TextView t(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(null,Typeface.BOLD);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 private LinearLayout card(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);v.setPadding(dp(12),dp(10),dp(12),dp(10));v.setBackground(bg(PANEL,12));return v;}
 private void gap(int h){Space s=new Space(this);body.addView(s,new LinearLayout.LayoutParams(1,dp(h)));}
 private TextView pill(String s,int color){TextView v=t(s,10,Color.WHITE,true);v.setGravity(Gravity.CENTER);v.setBackground(bg(color,9));v.setPadding(dp(8),0,dp(8),0);return v;}
 private void nav(LinearLayout root,int active){LinearLayout n=new LinearLayout(this);n.setBackgroundColor(Color.rgb(7,27,46));String[] a={"⌂\\nAna Sayfa","▥\\nPiyasalar","◎\\nRadar","▣\\nPortföy","•••\\nDiğer"};for(int i=0;i<5;i++){TextView v=t(a[i],9,i==active?BLUE:MUTED,i==active);v.setGravity(Gravity.CENTER);n.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(n);}
 private LinearLayout detailRoot(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(10));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));return root;}
 private void stockHead(){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.addView(t("‹",24,Color.WHITE,true),new LinearLayout.LayoutParams(dp(28),dp(42)));TextView logo=pill("✈",RED);h.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);names.addView(t("THYAO",16,Color.WHITE,true));names.addView(t("Türk Hava Yolları A.Ş.",9,MUTED,false));h.addView(names,new LinearLayout.LayoutParams(0,dp(45),1));h.addView(t("＋  ★",19,Color.rgb(245,178,43),true),new LinearLayout.LayoutParams(dp(68),dp(42)));body.addView(h);body.addView(t("277,20 ₺",27,Color.WHITE,true));body.addView(t("+4,90  (+1,80%)",15,GREEN,true));body.addView(t("15.09.2026 14:32",9,MUTED,false));gap(8);LinearLayout tabs=new LinearLayout(this);String[] ts={"Genel","Grafik","Haber","KAP","Finansal"};for(int i=0;i<5;i++){TextView x=t(ts[i],10,i==0?Color.WHITE:MUTED,i==0);x.setGravity(Gravity.CENTER);final int k=i;x.setOnClickListener(v->{if(k==0)showDetail();else if(k==1)showChart();else if(k==2||k==3)showNews();else if(k==4)showFinancial();});tabs.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(tabs);gap(8);}
 @Override public void onCreate(Bundle b){super.onCreate(b);String screen=getIntent().getStringExtra("screen");if("detail".equals(screen))showDetail();else if("chart".equals(screen))showChart();else if("news".equals(screen))showNews();else if("financial".equals(screen))showFinancial();else showHome();}
 @Override public void onBackPressed(){showHome();}
 private void showHome(){
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);
  ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(14),dp(14),dp(14),dp(14));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);
  TextView mark=t("BR",12,Color.WHITE,true);mark.setGravity(Gravity.CENTER);mark.setBackground(bg(BLUE,10));head.addView(mark,new LinearLayout.LayoutParams(dp(34),dp(34)));
  LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);TextView name=t("BORSA RADAR",18,Color.WHITE,true);TextView sub=t("Akıllı piyasa takip merkezi",9,MUTED,false);brand.addView(name);brand.addView(sub);head.addView(brand,new LinearLayout.LayoutParams(0,dp(46),1));
  TextView bell=t("●",16,BLUE,true);bell.setGravity(Gravity.CENTER);head.addView(bell,new LinearLayout.LayoutParams(dp(36),dp(36)));body.addView(head);gap(10);
  TextView search=t("⌕   Hisse, endeks veya şirket ara",12,Color.rgb(190,207,222),false);search.setPadding(dp(12),0,dp(12),0);search.setBackground(bg(PANEL,12));body.addView(search,new LinearLayout.LayoutParams(-1,dp(44)));gap(8);
  LinearLayout markets=new LinearLayout(this);String[] ms={"BIST","Almanya","ABD","Tümü"};for(int i=0;i<4;i++){TextView x=t(ms[i],11,i==0?Color.WHITE:MUTED,true);x.setGravity(Gravity.CENTER);x.setBackground(bg(i==0?BLUE:PANEL,10));markets.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(markets);gap(14);
  body.addView(t("Stratejiler",15,Color.WHITE,true));gap(6);
  String[] a={"⚡  Hızlı Tarama\nAnlık fırsatlar","↗  Kısa Vade\nGünlük / saatlik","◆  Temettü\nDüzenli gelir","◎  Uzun Vade\nGüçlü şirketler"};for(int r=0;r<2;r++){LinearLayout row=new LinearLayout(this);for(int j=0;j<2;j++){LinearLayout c=card();TextView x=t(a[r*2+j],11,Color.WHITE,true);c.addView(x,new LinearLayout.LayoutParams(-1,-1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(66),1);lp.setMargins(dp(3),dp(3),dp(3),dp(3));row.addView(c,lp);}body.addView(row);}gap(14);
  LinearLayout ttl=new LinearLayout(this);ttl.addView(t("Günün Öne Çıkanları",15,Color.WHITE,true),new LinearLayout.LayoutParams(0,dp(28),1));TextView all=t("Tümünü Gör  ›",10,BLUE,true);all.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);ttl.addView(all,new LinearLayout.LayoutParams(dp(100),dp(28)));body.addView(ttl);gap(5);
  String[][] stocks={{"THYAO","312,50","%2,14","AL"},{"BIMAS","548,00","%1,28","İZLE"},{"TCELL","104,60","%-0,38","SAT"}};for(String[] s:stocks){LinearLayout c=card();c.setOrientation(LinearLayout.HORIZONTAL);TextView code=t(s[0],13,Color.WHITE,true);if(s[0].equals("THYAO")){c.setOnClickListener(v->showDetail());code.setOnClickListener(v->showDetail());}c.addView(code,new LinearLayout.LayoutParams(0,dp(36),1));TextView p=t(s[1]+"   "+s[2],11,s[2].contains("-")?RED:GREEN,true);p.setGravity(Gravity.CENTER);c.addView(p,new LinearLayout.LayoutParams(dp(145),dp(36)));TextView sig=t(s[3],10,s[3].equals("AL")?GREEN:s[3].equals("SAT")?RED:Color.rgb(239,177,57),true);sig.setGravity(Gravity.CENTER);c.addView(sig,new LinearLayout.LayoutParams(dp(52),dp(36)));body.addView(c);gap(5);}
  gap(8);body.addView(t("Piyasa Özeti",15,Color.WHITE,true));gap(5);LinearLayout idx=new LinearLayout(this);String[] ni={"BIST 100\n10.984  +%0,82","DAX\n19.212  +%0,31","S&P 500\n6.742  +%0,46","NASDAQ\n22.518  +%0,55"};for(String q:ni){LinearLayout c=card();c.addView(t(q,9,Color.WHITE,true));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(55),1);lp.setMargins(dp(2),0,dp(2),0);idx.addView(c,lp);}body.addView(idx);gap(12);
  LinearLayout news=card();news.addView(t("SON DAKİKA",9,RED,true));news.addView(t("Piyasalardaki önemli gelişmeler burada gösterilecek.",11,Color.WHITE,true));news.addView(t("Haber ve veri bağlantıları sonraki aşamada bağlanacak.",9,MUTED,false));body.addView(news);
  LinearLayout nav=new LinearLayout(this);nav.setPadding(dp(3),dp(4),dp(3),dp(5));nav.setBackgroundColor(Color.rgb(7,27,46));String[] n={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(n[i],9,i==0?BLUE:MUTED,i==0);v.setGravity(Gravity.CENTER);nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showDetail(){
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);
  ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(10));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.addView(t("‹",24,Color.WHITE,true),new LinearLayout.LayoutParams(dp(30),dp(42)));TextView logo=pill("✈",RED);h.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t("THYAO",16,Color.WHITE,true));nm.addView(t("Türk Hava Yolları A.Ş.",9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));h.addView(t("＋  ★",18,Color.rgb(245,178,43),true),new LinearLayout.LayoutParams(dp(70),dp(42)));body.addView(h);
  body.addView(t("277,20 ₺",27,Color.WHITE,true));body.addView(t("+4,90  (+1,80%)",14,GREEN,true));body.addView(t("15.09.2026 14:32",9,MUTED,false));gap(7);
  LinearLayout tabs=new LinearLayout(this);String[] ts={"Genel","Grafik","Haber","KAP","Finansal"};for(int i=0;i<5;i++){TextView x=t(ts[i],10,i==0?Color.WHITE:MUTED,i==0);x.setGravity(Gravity.CENTER);tabs.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(tabs);gap(8);
  LinearLayout stats=new LinearLayout(this);String[] ss={"Açılış\n274,00","Yüksek\n278,40","Düşük\n272,60","Hacim\n8,4M","Piyasa Değeri\n382,1 Mr ₺"};for(String s:ss){TextView x=t(s,9,Color.WHITE,false);x.setGravity(Gravity.CENTER);stats.addView(x,new LinearLayout.LayoutParams(0,dp(48),1));}body.addView(stats);gap(8);
  LinearLayout act=new LinearLayout(this);String[] aa={"AL","TUT","SAT"};int[] co={GREEN,Color.rgb(238,151,35),RED};for(int i=0;i<3;i++){TextView x=pill(aa[i],co[i]);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(44),1);lp.setMargins(dp(3),0,dp(3),0);act.addView(x,lp);}body.addView(act);gap(13);
  body.addView(t("Hızlı Bilgiler",14,Color.WHITE,true));gap(5);LinearLayout quick=new LinearLayout(this);String[] q={"F/K\n5,8","PD/DD\n0,9","Temettü Verimi\n%3,2","Beta\n1,1"};for(String s:q){LinearLayout ca=card();TextView x=t(s,10,Color.WHITE,false);x.setGravity(Gravity.CENTER);ca.addView(x);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(62),1);lp.setMargins(dp(2),0,dp(2),0);quick.addView(ca,lp);}body.addView(quick);gap(13);
  body.addView(t("Günlük Aralık",11,Color.WHITE,true));ProgressBar p1=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p1.setMax(100);p1.setProgress(76);body.addView(p1,new LinearLayout.LayoutParams(-1,dp(18)));body.addView(t("272,60                                                       278,40",9,MUTED,false));gap(8);
  body.addView(t("52 Hafta Aralığı",11,Color.WHITE,true));ProgressBar p2=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p2.setMax(100);p2.setProgress(72);body.addView(p2,new LinearLayout.LayoutParams(-1,dp(18)));body.addView(t("193,50                                                       298,75",9,MUTED,false));
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showChart(){
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);
  ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(10));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.addView(t("‹",24,Color.WHITE,true),new LinearLayout.LayoutParams(dp(30),dp(42)));TextView logo=pill("✈",RED);h.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t("THYAO",16,Color.WHITE,true));nm.addView(t("Türk Hava Yolları A.Ş.",9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));h.addView(t("＋  ★",18,Color.rgb(245,178,43),true),new LinearLayout.LayoutParams(dp(70),dp(42)));body.addView(h);
  body.addView(t("277,20 ₺",27,Color.WHITE,true));body.addView(t("+4,90  (+1,80%)",14,GREEN,true));gap(6);
  LinearLayout tabs=new LinearLayout(this);String[] ts={"Genel","Grafik","Haber","KAP","Finansal"};for(int i=0;i<5;i++){TextView x=t(ts[i],10,i==1?Color.WHITE:MUTED,i==1);x.setGravity(Gravity.CENTER);final int k=i;x.setOnClickListener(v->{if(k==0)showDetail();else if(k==1)showChart();else if(k==2||k==3)showNews();else if(k==4)showFinancial();});tabs.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(tabs);gap(8);
  LinearLayout tf=new LinearLayout(this);String[] fs={"1G","1H","1A","3A","6A","1Y","2Y"};for(int i=0;i<7;i++){TextView x=t(fs[i],9,i==2?Color.WHITE:MUTED,true);x.setGravity(Gravity.CENTER);x.setBackground(bg(i==2?BLUE:PANEL,8));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(30),1);lp.setMargins(dp(2),0,dp(2),0);tf.addView(x,lp);}body.addView(tf);gap(8);
  LinearLayout chart=card();chart.addView(t("MA(20) 273,40     MA(50) 265,12     MA(200) 238,56",9,MUTED,false));chart.addView(t("       │  ╷     ╻ ╷    ╻\n  278  │  ┃ ╷   ┃ ┃ ╷  ┃\n  274  │╷ ┃ ┃ ╻ ┃ ┃ ┃╻ ┃   277,20\n  270  │┃ ┃ ┃ ┃ ┃ ┃ ┃┃ ┃\n  266  │┃ ╵ ┃ ┃ ╵ ┃ ┃┃ ╵\n       └────────────────────",13,Color.WHITE,false));chart.addView(t("Hacim   ▂ ▅ ▃ ▇ ▄ ▆ ▃ ▅ ▇ ▄ ▆",10,BLUE,true));body.addView(chart,new LinearLayout.LayoutParams(-1,dp(210)));gap(8);
  LinearLayout inds=new LinearLayout(this);String[] ii={"RSI","MACD","Stoch","CCI","BB"};for(String s:ii){TextView x=pill(s,s.equals("RSI")?BLUE:PANEL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(30),1);lp.setMargins(dp(2),0,dp(2),0);inds.addView(x,lp);}body.addView(inds);gap(8);
  LinearLayout rsi=card();rsi.addView(t("RSI (14)                                      62,4",10,Color.WHITE,true));rsi.addView(t("70  ─────────────────────\n          ╱╲      ╱╲\n50  ───╱───╲──╱───╲────\n30  ─────────────────────",11,GREEN,false));body.addView(rsi,new LinearLayout.LayoutParams(-1,dp(105)));
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showNews(){
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(10));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.addView(t("‹",24,Color.WHITE,true),new LinearLayout.LayoutParams(dp(30),dp(42)));TextView logo=pill("✈",RED);h.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t("THYAO",16,Color.WHITE,true));nm.addView(t("Türk Hava Yolları A.Ş.",9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));h.addView(t("＋  ★",18,Color.rgb(245,178,43),true),new LinearLayout.LayoutParams(dp(70),dp(42)));body.addView(h);body.addView(t("277,20 ₺",27,Color.WHITE,true));body.addView(t("+4,90  (+1,80%)",14,GREEN,true));gap(6);
  LinearLayout tabs=new LinearLayout(this);String[] ts={"Genel","Grafik","Haber","KAP","Finansal"};for(int i=0;i<5;i++){TextView x=t(ts[i],10,i==2?Color.WHITE:MUTED,i==2);x.setGravity(Gravity.CENTER);final int k=i;x.setOnClickListener(v->{if(k==0)showDetail();else if(k==1)showChart();else if(k==2||k==3)showNews();else if(k==4)showFinancial();});tabs.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(tabs);gap(8);
  LinearLayout filters=new LinearLayout(this);String[] fs={"Tümü","KAP","Medya","Analist"};for(int i=0;i<4;i++){TextView x=pill(fs[i],i==0?BLUE:PANEL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(30),1);lp.setMargins(dp(2),0,dp(2),0);filters.addView(x,lp);}body.addView(filters);gap(8);
  String[][] n={{"14:21","THYAO, Airbus ile 150 uçak için niyet mektubu imzaladı","Bloomberg","Pozitif"},{"12:10","THY’den yeni hat açıklaması: Sydney seferleri başlıyor","AA","Pozitif"},{"10:45","Analistler THYAO hedef fiyatlarını yükseltti","İş Yatırım","Pozitif"},{"09:32","THYAO 2. çeyrek yolcu verileri açıklandı","KAP","Nötr"},{"Dün 18:20","Uluslararası havayolları hisselerinde genel yükseliş","Reuters","Pozitif"}};for(String[] q:n){LinearLayout ca=card();ca.addView(t(q[0]+"   "+q[2],9,MUTED,false));ca.addView(t(q[1],11,Color.WHITE,true));ca.addView(t(q[3],9,q[3].equals("Pozitif")?GREEN:Color.rgb(239,177,57),true));body.addView(ca);gap(6);}
  TextView all=t("Tüm Haberleri Gör",11,Color.WHITE,true);all.setGravity(Gravity.CENTER);all.setBackground(bg(BLUE,10));body.addView(all,new LinearLayout.LayoutParams(-1,dp(42)));
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showFinancial(){
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(10));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showHome());h.addView(back,new LinearLayout.LayoutParams(dp(30),dp(42)));TextView logo=pill("✈",RED);h.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t("THYAO",16,Color.WHITE,true));nm.addView(t("Türk Hava Yolları A.Ş.",9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));body.addView(h);body.addView(t("277,20 ₺",27,Color.WHITE,true));body.addView(t("+4,90  (+1,80%)",14,GREEN,true));gap(6);
  LinearLayout tabs=new LinearLayout(this);String[] ts={"Genel","Grafik","Haber","KAP","Finansal"};for(int i=0;i<5;i++){TextView x=t(ts[i],10,i==4?Color.WHITE:MUTED,i==4);x.setGravity(Gravity.CENTER);final int k=i;x.setOnClickListener(v->{if(k==0)showDetail();else if(k==1)showChart();else if(k==2||k==3)showNews();else showFinancial();});tabs.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(tabs);gap(8);
  LinearLayout sub=new LinearLayout(this);String[] st={"Özet","Gelir Tablosu","Bilanço","Nakit Akışı"};for(int i=0;i<4;i++){TextView x=pill(st[i],i==0?BLUE:PANEL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(30),1);lp.setMargins(dp(2),0,dp(2),0);sub.addView(x,lp);}body.addView(sub);gap(10);body.addView(t("Temel Finansal Veriler (Son 12 Ay)",14,Color.WHITE,true));gap(5);
  String[][] rows={{"Piyasa Değeri","382,1 Mr ₺"},{"F/K","5,8"},{"PD/DD","0,9"},{"FD/FAVÖK","4,1"},{"Hisse Başına Kar","47,8 ₺"},{"Temettü Verimi","%3,2"},{"Özkaynak Karlılığı","%15,4"},{"Net Kar (Son Çeyrek)","22,4 Mr ₺"},{"Gelir (Son Çeyrek)","176,3 Mr ₺"},{"Yıllık Gelir Büyümesi","%32,1"},{"Yıllık Kar Büyümesi","%48,7"},{"Sektör","Ulaştırma"},{"52 Hafta En Düşük","193,50 ₺"},{"52 Hafta En Yüksek","298,75 ₺"}};for(String[] q:rows){LinearLayout row=new LinearLayout(this);row.setPadding(dp(8),dp(7),dp(8),dp(7));row.setBackground(bg(PANEL,7));row.addView(t(q[0],10,MUTED,false),new LinearLayout.LayoutParams(0,dp(26),1));TextView val=t(q[1],10,Color.WHITE,true);val.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);row.addView(val,new LinearLayout.LayoutParams(dp(130),dp(26)));body.addView(row);gap(2);}
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);if(i==0)v.setOnClickListener(x->showHome());nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }
}
