package com.kulanoglu.borsaradar;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.Typeface;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.*;

public class ReferenceUiActivity extends Activity {
 private final int NAVY=Color.rgb(5,18,34), PANEL=Color.rgb(12,34,59), BLUE=Color.rgb(36,118,255), MUTED=Color.rgb(137,163,188), GREEN=Color.rgb(31,191,126), AMBER=Color.rgb(245,158,11), RED=Color.rgb(238,82,83);
 private LinearLayout body; private LinearLayout radarRows; private TextView radarProgress; private String radarFilter="Tümü"; private int screen=0;
 private int previousScreen=0; private String selectedSymbol="THYAO"; private String lastRadarSymbol="THYAO"; private int radarIndex=0; private boolean scanDone=false; private boolean radarLoading=false; private String scanMode="Teknik + Temel";
 private String selectedMarket="BIST";
 private ShortPulseEngine.Profile selectedProfile=ShortPulseEngine.Profile.BALANCED; private final java.util.ArrayList<String[]> cachedRadarRows=new java.util.ArrayList<>();
 private final java.util.HashMap<String,java.util.ArrayList<String[]>> radarCacheByMarket=new java.util.HashMap<>();
 private final java.util.HashMap<String,Boolean> scanDoneByMarket=new java.util.HashMap<>();
 private final String[] radarSymbols={"THYAO","BIMAS","TCELL","KRDMD","PETKM","ENERY","KCHOL","TUPRS","GARAN","AKBNK","YKBNK","SASA","FROTO","TTKOM","GWIND","AAGYO","DUNYH","KLRHO","EREGL","SISE","SAHOL","ISCTR","HALKB","VAKBN","TOASO","TAVHL","PGSUS","ARCLK","VESTL","MGROS","ULKER","AEFES","CCOLA","DOAS","EKGYO","OYAKC","KOZAL","KOZAA","IPEKE","ASTOR","ENKAI","HEKTS","GUBRF","ALARK","ODAS","KONTR","GESAN","EUPWR","MIATK","REEDR","TABGD","MAVI","MPARK","SOKM","TTRAK","OTKAR","KARSN","TMSN","AKSA","AKSEN","ZOREN","AYDEM","KCAER","CIMSA","AKCNS","BTCIM","BRISA","KORDS","LOGO","NETAS","KAREL","SELEC","ECILC","DEVA","TURSG","ANHYT","AGESA","TSKB","SKBNK","ALBRK","ISMEN","DOHOL","GLYHO","GSRAY","FENER","BJKAS"};
 private final String[] germanyRadarSymbols={"SAP.DE","SIE.DE","ALV.DE","DTE.DE","MBG.DE","BMW.DE","BAS.DE","IFX.DE","ADS.DE","DBK.DE","RWE.DE","MUV2.DE","VOW3.DE","HEN3.DE","BEI.DE","FRE.DE","HEI.DE","MTX.DE","QIA.DE","SY1.DE"};
 private final String[] usaRadarSymbols={"AAPL","MSFT","NVDA","AMZN","GOOGL","META","TSLA","AVGO","AMD","NFLX","JPM","V","MA","COST","WMT","KO","PEP","XOM","JNJ","ORCL"};
 private String[] radarUniverse(){if("Almanya".equals(selectedMarket))return germanyRadarSymbols;if("ABD".equals(selectedMarket))return usaRadarSymbols;if("Tümü".equals(selectedMarket)){String[] all=new String[radarSymbols.length+germanyRadarSymbols.length+usaRadarSymbols.length];System.arraycopy(radarSymbols,0,all,0,radarSymbols.length);System.arraycopy(germanyRadarSymbols,0,all,radarSymbols.length,germanyRadarSymbols.length);System.arraycopy(usaRadarSymbols,0,all,radarSymbols.length+germanyRadarSymbols.length,usaRadarSymbols.length);return all;}
 private String[][] featuredForMarket(){
  if("Almanya".equals(selectedMarket))return new String[][]{{"SAP.DE","","",""},{"SIE.DE","","",""},{"ALV.DE","","",""}};
  if("ABD".equals(selectedMarket))return new String[][]{{"NVDA","","",""},{"AAPL","","",""},{"MSFT","","",""}};
  if("Tümü".equals(selectedMarket))return new String[][]{{"THYAO","","",""},{"SAP.DE","","",""},{"NVDA","","",""}};
  return new String[][]{{"THYAO","","",""},{"BIMAS","","",""},{"TCELL","","",""}};
 }return radarSymbols;} private TextView livePrice,liveChange,liveTime,chartPrice,chartChange,computedSignal,valueHistory,paperValue,technicalRows,technicalSummary,targetRiskData,financialData,chartInfo,homeMarketSummary; private LinearLayout featuredContainer; private LinearLayout horizonSignals; private LinearLayout liveStats; private final java.util.concurrent.ExecutorService uiIo=java.util.concurrent.Executors.newFixedThreadPool(4);
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 private android.graphics.drawable.GradientDrawable bg(int c,int r){android.graphics.drawable.GradientDrawable g=new android.graphics.drawable.GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 private TextView t(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(null,Typeface.BOLD);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 private LinearLayout card(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);v.setPadding(dp(12),dp(10),dp(12),dp(10));v.setBackground(bg(PANEL,12));return v;}
 private void gap(int h){Space s=new Space(this);body.addView(s,new LinearLayout.LayoutParams(1,dp(h)));}
 private String companyName(String s){java.util.Map<String,String>m=new java.util.HashMap<>();m.put("THYAO","Türk Hava Yolları A.Ş.");m.put("BIMAS","BİM Birleşik Mağazalar");m.put("TCELL","Turkcell");m.put("ASELS","Aselsan");m.put("KRDMD","Kardemir D");m.put("PETKM","Petkim");m.put("ENERY","Enerya Enerji");m.put("KCHOL","Koç Holding");m.put("TUPRS","Tüpraş");m.put("GARAN","Garanti BBVA");m.put("AKBNK","Akbank");m.put("YKBNK","Yapı Kredi");m.put("SASA","SASA Polyester");m.put("NVDA","NVIDIA");return m.containsKey(s)?m.get(s):s;}
 private String currency(String s){String n=MarketDataService.normalizeSymbol(s);if(n.endsWith(".DE"))return " €";if(n.endsWith(".IS"))return " ₺";return " $";}
 private String marketForSymbol(String s){String n=MarketDataService.normalizeSymbol(s);if(n.endsWith(".DE"))return "Almanya";if(n.endsWith(".IS"))return "BIST";return "ABD";}
 private String sourceBadge(String s){String x=MarketDataService.lastGoodSource(s);return x.isEmpty()?"Kaynak aranıyor":"Kaynak: "+x;}
 private String profileLabel(){return selectedProfile==ShortPulseEngine.Profile.FAST?"HIZLI":selectedProfile==ShortPulseEngine.Profile.CONFIRMED?"TEYİTLİ":"DENGELİ";}
 private String marketStatus(){return selectedMarket+" • "+profileLabel()+" • "+MarketDataService.healthySourceCount()+"/"+MarketDataService.activeSourceCount()+" aktif kaynak";}
 private void addCompactLiveQuote(){final TextView p=t("Veri yükleniyor…",27,Color.WHITE,true),ch=t("",14,MUTED,true);body.addView(p);body.addView(ch);final String symbol=selectedSymbol;uiIo.execute(()->{try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(symbol,"5d","5m",200);if(d==null||d.size()<2)return;double price=d.get(d.size()-1).close,prev=d.get(d.size()-2).close;MarketDataService.Spot sp=MarketDataService.latestSpot(symbol);if(sp!=null&&sp.price>0)price=sp.price;final double fp=price,fc=price-prev,pc=prev==0?0:(price-prev)/prev*100d;runOnUiThread(()->{if(!symbol.equals(selectedSymbol))return;p.setText(String.format(java.util.Locale.GERMANY,"%.2f%s",fp,currency(symbol)));ch.setText(String.format(java.util.Locale.GERMANY,"%+.2f (%+.2f%%)",fc,pc));ch.setTextColor(fc>=0?GREEN:RED);});}catch(Exception ignored){runOnUiThread(()->p.setText("Fiyat alınamadı"));}});}
 private TextView pill(String s,int color){TextView v=t(s,10,Color.WHITE,true);v.setGravity(Gravity.CENTER);v.setBackground(bg(color,9));v.setPadding(dp(8),0,dp(8),0);return v;}
 private void nav(LinearLayout root,int active){LinearLayout n=new LinearLayout(this);n.setBackgroundColor(Color.rgb(7,27,46));String[] a={"⌂\\nAna Sayfa","▥\\nPiyasalar","◎\\nRadar","▣\\nPortföy","•••\\nDiğer"};for(int i=0;i<5;i++){TextView v=t(a[i],9,i==active?BLUE:MUTED,i==active);v.setGravity(Gravity.CENTER);final int k=i;v.setOnClickListener(x->{if(k==0)showHome();else if(k==1)showMarkets();else if(k==2)showRadar();else if(k==3)showPortfolio();else showMore();});n.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(n);}
 private void showMarkets(){previousScreen=screen;screen=11;LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(14),dp(14),dp(14),dp(14));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));body.addView(t("PİYASALAR",20,Color.WHITE,true));body.addView(t(marketStatus(),10,GREEN,true));body.addView(t("Piyasa seç • seçim Ana Sayfa ve Radar evrenini değiştirir",10,MUTED,false));gap(12);String[] ms={"BIST","Almanya","ABD","Tümü"};for(String m:ms){TextView v=pill((selectedMarket.equals(m)?"✓ ":"")+m,selectedMarket.equals(m)?BLUE:PANEL);v.setOnClickListener(x->{String old=selectedMarket;radarCacheByMarket.put(old,new java.util.ArrayList<>(cachedRadarRows));saveRadarCache(old);selectedMarket=m;getSharedPreferences("borsaradar",MODE_PRIVATE).edit().putString("selectedMarket",m).apply();loadRadarCache(m);showMarkets();});body.addView(v,new LinearLayout.LayoutParams(-1,dp(46)));gap(8);}nav(root,1);setContentView(root);}
 private LinearLayout detailRoot(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(10));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));return root;}
 private void stockHead(){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->{if(previousScreen==2)showRadar();else showHome();});h.addView(back,new LinearLayout.LayoutParams(dp(28),dp(42)));TextView logo=pill("BR",BLUE);h.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);names.addView(t(selectedSymbol,16,Color.WHITE,true));names.addView(t(companyName(selectedSymbol),9,MUTED,false));h.addView(names,new LinearLayout.LayoutParams(0,dp(45),1));h.addView(t("＋  ★",19,Color.rgb(245,178,43),true),new LinearLayout.LayoutParams(dp(68),dp(42)));body.addView(h);addCompactLiveQuote();gap(8);LinearLayout tabs=new LinearLayout(this);String[] ts={"Genel","Grafik","Haber","KAP","Finansal"};for(int i=0;i<5;i++){TextView x=t(ts[i],10,i==0?Color.WHITE:MUTED,i==0);x.setGravity(Gravity.CENTER);final int k=i;x.setOnClickListener(v->{if(k==0)showDetail();else if(k==1)showChart();else if(k==2||k==3)showNews();else showFinancial();});tabs.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(tabs);gap(8);}
 @Override public void onCreate(Bundle b){super.onCreate(b);android.content.SharedPreferences p=getSharedPreferences("borsaradar",MODE_PRIVATE);lastRadarSymbol=p.getString("lastRadarSymbol","THYAO");selectedSymbol=lastRadarSymbol;scanDone=p.getBoolean("scanDone",false);scanMode=p.getString("scanMode","Teknik + Temel");selectedMarket=p.getString("selectedMarket","BIST");
  try{selectedProfile=ShortPulseEngine.Profile.valueOf(p.getString("selectedProfile","BALANCED"));}catch(Exception ignored){selectedProfile=ShortPulseEngine.Profile.BALANCED;}String screen=getIntent().getStringExtra("screen");if("detail".equals(screen))showDetail();else if("chart".equals(screen))showChart();else if("news".equals(screen))showNews();else if("financial".equals(screen))showFinancial();else if("radar".equals(screen))showRadar();else if("technical".equals(screen))showTechnical();else if("target".equals(screen))showTargetRisk();else if("portfolio".equals(screen))showPortfolio();else if("strategy".equals(screen))showStrategy();else if("more".equals(screen))showMore();else showHome();}
 @Override public void onBackPressed(){if(screen==4||screen==5||screen==6||screen==7||screen==8)showDetail();else if(screen==3){if(previousScreen==2)showRadar();else if(previousScreen==9)showPortfolio();else showHome();}else if(screen==2||screen==9||screen==10||screen==11)showHome();else super.onBackPressed();}
 private void showHome(){ previousScreen=screen; screen=1;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);
  ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(14),dp(14),dp(14),dp(14));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);
  TextView mark=t("BR",12,Color.WHITE,true);mark.setGravity(Gravity.CENTER);mark.setBackground(bg(BLUE,10));head.addView(mark,new LinearLayout.LayoutParams(dp(34),dp(34)));
  LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);TextView name=t("BORSA RADAR",18,Color.WHITE,true);TextView sub=t("Akıllı piyasa takip merkezi",9,MUTED,false);brand.addView(name);brand.addView(sub);head.addView(brand,new LinearLayout.LayoutParams(0,dp(46),1));
  TextView bell=t("●",16,BLUE,true);bell.setGravity(Gravity.CENTER);head.addView(bell,new LinearLayout.LayoutParams(dp(36),dp(36)));body.addView(head);gap(10);
  TextView search=t("⌕   Hisse, endeks veya şirket ara",12,Color.rgb(190,207,222),false);search.setPadding(dp(12),0,dp(12),0);search.setBackground(bg(PANEL,12));body.addView(search,new LinearLayout.LayoutParams(-1,dp(44)));gap(8);
  LinearLayout markets=new LinearLayout(this);String[] ms={"BIST","Almanya","ABD","Tümü"};for(int i=0;i<4;i++){final String market=ms[i];boolean active=market.equals(selectedMarket);TextView x=t(market,11,active?Color.WHITE:MUTED,true);x.setGravity(Gravity.CENTER);x.setBackground(bg(active?BLUE:PANEL,10));x.setOnClickListener(v->{String oldMarket=selectedMarket;java.util.ArrayList<String[]> oldCache=new java.util.ArrayList<>(cachedRadarRows);radarCacheByMarket.put(oldMarket,oldCache);saveRadarCache(oldMarket);scanDoneByMarket.put(oldMarket,scanDone);selectedMarket=market;getSharedPreferences("borsaradar",MODE_PRIVATE).edit().putString("selectedMarket",market).apply();java.util.ArrayList<String[]> next=radarCacheByMarket.get(market);cachedRadarRows.clear();if(next!=null)cachedRadarRows.addAll(next);scanDone=Boolean.TRUE.equals(scanDoneByMarket.get(market));showHome();});markets.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(markets);gap(14);
  body.addView(t("Stratejiler",15,Color.WHITE,true));gap(6);
  String[] a={"⚡  Hızlı Tarama\nAnlık fırsatlar","↗  Kısa Vade\nGünlük / saatlik","◆  Temettü\nDüzenli gelir","◎  Uzun Vade\nGüçlü şirketler"};for(int r=0;r<2;r++){LinearLayout row=new LinearLayout(this);for(int j=0;j<2;j++){LinearLayout c=card();TextView x=t(a[r*2+j],11,Color.WHITE,true);c.addView(x,new LinearLayout.LayoutParams(-1,-1));c.setOnClickListener(v->showStrategy());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(66),1);lp.setMargins(dp(3),dp(3),dp(3),dp(3));row.addView(c,lp);}body.addView(row);}gap(14);
  LinearLayout ttl=new LinearLayout(this);ttl.addView(t("Günün Öne Çıkanları",15,Color.WHITE,true),new LinearLayout.LayoutParams(0,dp(28),1));TextView all=t("Tümünü Gör  ›",10,BLUE,true);all.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);ttl.addView(all,new LinearLayout.LayoutParams(dp(100),dp(28)));body.addView(ttl);gap(5);
  featuredContainer=new LinearLayout(this);featuredContainer.setOrientation(LinearLayout.VERTICAL);body.addView(featuredContainer);loadFeaturedHome();gap(8);
  body.addView(t("Piyasa Özeti",15,Color.WHITE,true));gap(5);homeMarketSummary=t("Canlı piyasa özeti yükleniyor…",10,MUTED,true);homeMarketSummary.setPadding(dp(10),dp(10),dp(10),dp(10));homeMarketSummary.setBackground(bg(PANEL,9));body.addView(homeMarketSummary);loadHomeMarketSummary();gap(12);
  LinearLayout news=card();news.addView(t("SON DAKİKA",9,RED,true));news.addView(t("Piyasalardaki önemli gelişmeler burada gösterilecek.",11,Color.WHITE,true));news.addView(t("Haber ve veri bağlantıları sonraki aşamada bağlanacak.",9,MUTED,false));body.addView(news);
  LinearLayout nav=new LinearLayout(this);nav.setPadding(dp(3),dp(4),dp(3),dp(5));nav.setBackgroundColor(Color.rgb(7,27,46));String[] n={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(n[i],9,i==0?BLUE:MUTED,i==0);v.setGravity(Gravity.CENTER);final int k=i;v.setOnClickListener(x->{if(k==0)showHome();else if(k==1)showMarkets();else if(k==2)showRadar();else if(k==3)showPortfolio();else showMore();});nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showDetail(){ previousScreen=screen; screen=3; syncRadarIndex();
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);
  ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(10));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->{if(previousScreen==2)showRadar();else if(previousScreen==3)showPortfolio();else showHome();});h.addView(back,new LinearLayout.LayoutParams(dp(30),dp(42))); TextView prev=t("‹",20,MUTED,true);prev.setGravity(Gravity.CENTER);prev.setOnClickListener(v->moveRadar(-1));h.addView(prev,new LinearLayout.LayoutParams(dp(28),dp(42)));TextView logo=pill("✈",RED);h.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t(selectedSymbol,16,Color.WHITE,true));nm.addView(t(companyName(selectedSymbol),9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));h.addView(t("＋ ★",17,Color.rgb(245,178,43),true),new LinearLayout.LayoutParams(dp(58),dp(42))); TextView next=t("›",20,MUTED,true);next.setGravity(Gravity.CENTER);next.setOnClickListener(v->moveRadar(1));h.addView(next,new LinearLayout.LayoutParams(dp(28),dp(42)));body.addView(h);
  livePrice=t("Veri yükleniyor…",27,Color.WHITE,true);liveChange=t("",14,MUTED,true);liveTime=t("",9,MUTED,false);valueHistory=t("Değer geçmişi hesaplanıyor…",10,MUTED,false);paperValue=t("Kağıt değeri hesaplanıyor…",10,MUTED,true);body.addView(livePrice);body.addView(liveChange);body.addView(liveTime);body.addView(paperValue);body.addView(valueHistory);loadLiveQuote();loadPaperValue();loadValueHistory();gap(7);
  LinearLayout tabs=new LinearLayout(this);String[] ts={"Genel","Grafik","Haber","KAP","Finansal"};for(int i=0;i<5;i++){TextView x=t(ts[i],10,i==0?Color.WHITE:MUTED,i==0);x.setGravity(Gravity.CENTER);final int k=i;x.setOnClickListener(v->{if(k==0)showDetail();else if(k==1)showChart();else if(k==2||k==3)showNews();else showFinancial();});tabs.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(tabs);gap(8);
  liveStats=new LinearLayout(this);setLiveStats(null);body.addView(liveStats);gap(8);
  LinearLayout act=new LinearLayout(this);String[] aa={"HIZLI","DENGELİ","TEYİTLİ"};int[] co={GREEN,Color.rgb(238,151,35),BLUE};ShortPulseEngine.Profile[] profiles={ShortPulseEngine.Profile.FAST,ShortPulseEngine.Profile.BALANCED,ShortPulseEngine.Profile.CONFIRMED};for(int i=0;i<3;i++){TextView x=pill(aa[i],profiles[i]==selectedProfile?co[i]:PANEL);final ShortPulseEngine.Profile profile=profiles[i];x.setOnClickListener(v->{selectedProfile=profile;getSharedPreferences("borsaradar",MODE_PRIVATE).edit().putString("selectedProfile",profile.name()).apply();loadComputedSignal();Toast.makeText(this,"Profil: "+profile.name(),Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(44),1);lp.setMargins(dp(3),0,dp(3),0);act.addView(x,lp);}body.addView(act);computedSignal=t("Sinyal hesaplanıyor…",11,MUTED,true);computedSignal.setGravity(Gravity.CENTER);body.addView(computedSignal);horizonSignals=new LinearLayout(this);horizonSignals.setGravity(Gravity.CENTER);body.addView(horizonSignals,new LinearLayout.LayoutParams(-1,dp(58)));loadComputedSignal();gap(13);
  LinearLayout quickHead=new LinearLayout(this);quickHead.setGravity(Gravity.CENTER_VERTICAL);quickHead.addView(t("Hızlı Bilgiler",14,Color.WHITE,true),new LinearLayout.LayoutParams(0,dp(34),1));TextView technical=pill("Teknik Analiz ›",BLUE);technical.setOnClickListener(v->showTechnical());quickHead.addView(technical,new LinearLayout.LayoutParams(dp(115),dp(32)));body.addView(quickHead);gap(5);LinearLayout quick=new LinearLayout(this);String[] q={"F/K\n5,8","PD/DD\n0,9","Temettü Verimi\n%3,2","Beta\n1,1"};for(String s:q){LinearLayout ca=card();TextView x=t(s,10,Color.WHITE,false);x.setGravity(Gravity.CENTER);ca.addView(x);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(62),1);lp.setMargins(dp(2),0,dp(2),0);quick.addView(ca,lp);}body.addView(quick);gap(13);
  body.addView(t("Günlük Aralık",11,Color.WHITE,true));ProgressBar p1=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p1.setMax(100);p1.setProgress(76);body.addView(p1,new LinearLayout.LayoutParams(-1,dp(18)));body.addView(t("272,60                                                       278,40",9,MUTED,false));gap(8);
  body.addView(t("52 Hafta Aralığı",11,Color.WHITE,true));ProgressBar p2=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p2.setMax(100);p2.setProgress(72);body.addView(p2,new LinearLayout.LayoutParams(-1,dp(18)));body.addView(t("193,50                                                       298,75",9,MUTED,false));
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);final int k=i;v.setOnClickListener(x->{if(k==0)showHome();else if(k==1)showMarkets();else if(k==2)showRadar();else if(k==3)showPortfolio();else showMore();});nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showChart(){ screen=4;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);
  ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(10));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.addView(t("‹",24,Color.WHITE,true),new LinearLayout.LayoutParams(dp(30),dp(42)));TextView logo=pill("✈",RED);h.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t(selectedSymbol,16,Color.WHITE,true));nm.addView(t(companyName(selectedSymbol),9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));h.addView(t("＋  ★",18,Color.rgb(245,178,43),true),new LinearLayout.LayoutParams(dp(70),dp(42)));body.addView(h);
  chartPrice=t("Veri yükleniyor…",27,Color.WHITE,true);chartChange=t("",14,MUTED,true);body.addView(chartPrice);body.addView(chartChange);loadChartQuote();gap(6);
  LinearLayout tabs=new LinearLayout(this);String[] ts={"Genel","Grafik","Haber","KAP","Finansal"};for(int i=0;i<5;i++){TextView x=t(ts[i],10,i==1?Color.WHITE:MUTED,i==1);x.setGravity(Gravity.CENTER);final int k=i;x.setOnClickListener(v->{if(k==0)showDetail();else if(k==1)showChart();else if(k==2||k==3)showNews();else if(k==4)showFinancial();});tabs.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(tabs);gap(8);
  LinearLayout tf=new LinearLayout(this);String[] fs={"1G","1H","1A","3A","6A","1Y","2Y"};for(int i=0;i<7;i++){TextView x=t(fs[i],9,i==2?Color.WHITE:MUTED,true);x.setGravity(Gravity.CENTER);x.setBackground(bg(i==2?BLUE:PANEL,8));final String period=fs[i];x.setOnClickListener(v->{loadRealChart(period);loadChartAnalytics(period);});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(30),1);lp.setMargins(dp(2),0,dp(2),0);tf.addView(x,lp);}body.addView(tf);gap(8);
  chartInfo=t("Grafik ve indikatör verileri yükleniyor…",10,MUTED,false);chartInfo.setPadding(dp(10),dp(10),dp(10),dp(10));chartInfo.setBackground(bg(PANEL,8));body.addView(chartInfo,new LinearLayout.LayoutParams(-1,dp(210)));loadChartAnalytics("1A");gap(8);
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);final int k=i;v.setOnClickListener(x->{if(k==0)showHome();else if(k==1)showMarkets();else if(k==2)showRadar();else if(k==3)showPortfolio();else showMore();});nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void loadChartAnalytics(String period){final String symbol=selectedSymbol;final String p=period;uiIo.execute(()->{try{String range="1mo",interval="1d";if("1G".equals(p)){range="1d";interval="5m";}else if("1H".equals(p)){range="5d";interval="5m";}else if("3A".equals(p))range="3mo";else if("6A".equals(p))range="6mo";else if("1Y".equals(p))range="1y";else if("2Y".equals(p))range="2y";java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(symbol,range,interval,520);if(d==null||d.size()<10)return;int n=d.size(),e=n-1;double price=d.get(e).close,ma20=ema(d,Math.min(20,n),e),ma50=ema(d,Math.min(50,n),e),ma200=ema(d,Math.min(200,n),e),g=0,l=0,hi=-1e99,lo=1e99,vol=0;int start=Math.max(1,n-14);for(int i=start;i<n;i++){double z=d.get(i).close-d.get(i-1).close;if(z>=0)g+=z;else l-=z;hi=Math.max(hi,d.get(i).high);lo=Math.min(lo,d.get(i).low);vol+=d.get(i).volume;}double rsi=100-(100/(1+(l==0?100:g/l))),macd=ema(d,Math.min(12,n),e)-ema(d,Math.min(26,n),e),stoch=hi==lo?50:100*(price-lo)/(hi-lo);String txt=String.format(java.util.Locale.GERMANY,"%s • %s\nSon %.2f%s\nEMA20 %.2f • EMA50 %.2f • EMA200 %.2f\nRSI %.1f • MACD %.2f • Stoch %.1f\nAralık %.2f – %.2f • Hacim %s",symbol,p,price,currency(symbol),ma20,ma50,ma200,rsi,macd,stoch,lo,hi,formatVolume(vol));runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&chartInfo!=null)chartInfo.setText(txt);});}catch(Exception ex){runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&chartInfo!=null)chartInfo.setText("Grafik analizi alınamadı");});}});}
 private void showNews(){ screen=5;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(10));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.addView(t("‹",24,Color.WHITE,true),new LinearLayout.LayoutParams(dp(30),dp(42)));TextView logo=pill("✈",RED);h.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t(selectedSymbol,16,Color.WHITE,true));nm.addView(t(companyName(selectedTicker),9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));h.addView(t("＋  ★",18,Color.rgb(245,178,43),true),new LinearLayout.LayoutParams(dp(70),dp(42)));body.addView(h);addCompactLiveQuote();gap(6);
  LinearLayout tabs=new LinearLayout(this);String[] ts={"Genel","Grafik","Haber","KAP","Finansal"};for(int i=0;i<5;i++){TextView x=t(ts[i],10,i==2?Color.WHITE:MUTED,i==2);x.setGravity(Gravity.CENTER);final int k=i;x.setOnClickListener(v->{if(k==0)showDetail();else if(k==1)showChart();else if(k==2||k==3)showNews();else if(k==4)showFinancial();});tabs.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(tabs);gap(8);
  LinearLayout filters=new LinearLayout(this);String[] fs={"Tümü","KAP","Medya","Analist"};for(int i=0;i<4;i++){TextView x=pill(fs[i],i==0?BLUE:PANEL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(30),1);lp.setMargins(dp(2),0,dp(2),0);filters.addView(x,lp);}body.addView(filters);gap(8);
  String[][] n={{"14:21","THYAO, Airbus ile 150 uçak için niyet mektubu imzaladı","Bloomberg","Pozitif"},{"12:10","THY’den yeni hat açıklaması: Sydney seferleri başlıyor","AA","Pozitif"},{"10:45","Analistler THYAO hedef fiyatlarını yükseltti","İş Yatırım","Pozitif"},{"09:32","THYAO 2. çeyrek yolcu verileri açıklandı","KAP","Nötr"},{"Dün 18:20","Uluslararası havayolları hisselerinde genel yükseliş","Reuters","Pozitif"}};for(String[] q:n){LinearLayout ca=card();ca.addView(t(q[0]+"   "+q[2],9,MUTED,false));ca.addView(t(q[1],11,Color.WHITE,true));ca.addView(t(q[3],9,q[3].equals("Pozitif")?GREEN:Color.rgb(239,177,57),true));body.addView(ca);gap(6);}
  TextView all=t("Tüm Haberleri Gör",11,Color.WHITE,true);all.setOnClickListener(v->Toast.makeText(this,"Tüm "+selectedTicker+" haberleri",Toast.LENGTH_SHORT).show());all.setGravity(Gravity.CENTER);all.setBackground(bg(BLUE,10));body.addView(all,new LinearLayout.LayoutParams(-1,dp(42)));
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void loadFeaturedHome(){final String market=selectedMarket;final String[][] base=featuredForMarket();uiIo.execute(()->{final java.util.ArrayList<String[]> rows=new java.util.ArrayList<>();for(String[] q:base){String s=q[0];try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(s,"6mo","1d",180);if(d==null||d.size()<35){rows.add(new String[]{s,"—","—","VERİ YOK"});continue;}int n=d.size();double price=d.get(n-1).close,prev=d.get(n-2).close;MarketDataService.Spot sp=MarketDataService.latestSpot(s);if(sp!=null&&sp.price>0)price=sp.price;ShortPulseEngine.Result p=ShortPulseEngine.analyze(d,s,selectedProfile);double pct=prev==0?0:(price-prev)/prev*100;String sig=p.recommendation.contains("SAT")?"SAT":p.recommendation.contains("AL")?"AL":"İZLE";rows.add(new String[]{s,String.format(java.util.Locale.GERMANY,"%.2f%s",price,currency(s)),String.format(java.util.Locale.GERMANY,"%+.2f%%",pct),sig});}catch(Exception ex){rows.add(new String[]{s,"—","—","VERİ YOK"});}}runOnUiThread(()->{if(!market.equals(selectedMarket)||featuredContainer==null)return;featuredContainer.removeAllViews();for(String[] s:rows){LinearLayout card=card();card.setOrientation(LinearLayout.HORIZONTAL);TextView code=t(s[0],13,Color.WHITE,true);TextView pr=t(s[1]+"  "+s[2],10,s[2].startsWith("-")?RED:GREEN,true);pr.setGravity(Gravity.CENTER);TextView sig=t(s[3],9,"AL".equals(s[3])?GREEN:"SAT".equals(s[3])?RED:AMBER,true);sig.setGravity(Gravity.CENTER);final String sym=s[0];card.setOnClickListener(v->{selectedSymbol=sym;lastRadarSymbol=sym;getSharedPreferences("borsaradar",MODE_PRIVATE).edit().putString("lastRadarSymbol",sym).apply();showDetail();});card.addView(code,new LinearLayout.LayoutParams(0,dp(38),1));card.addView(pr,new LinearLayout.LayoutParams(dp(150),dp(38)));card.addView(sig,new LinearLayout.LayoutParams(dp(58),dp(38)));featuredContainer.addView(card);Space spc=new Space(this);featuredContainer.addView(spc,new LinearLayout.LayoutParams(1,dp(5)));}});});}
 private void loadHomeMarketSummary(){final String market=selectedMarket;final String[][] idx={{"BIST 100","^XU100"},{"DAX","^GDAXI"},{"S&P 500","^GSPC"},{"NASDAQ","^IXIC"}};uiIo.execute(()->{StringBuilder sb=new StringBuilder();for(String[] q:idx){try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(q[1],"5d","1d",10);if(d==null||d.size()<2){sb.append(q[0]).append("  —\n");continue;}double p=d.get(d.size()-1).close,prev=d.get(d.size()-2).close;MarketDataService.Spot spot=MarketDataService.latestSpot(q[1]);if(spot!=null&&spot.price>0)p=spot.price;double pct=prev==0?0:(p-prev)/prev*100;sb.append(String.format(java.util.Locale.GERMANY,"%s  %.2f  %+.2f%%\n",q[0],p,pct));}catch(Exception ex){sb.append(q[0]).append("  —\n");}}final String txt=sb.toString().trim();runOnUiThread(()->{if(market.equals(selectedMarket)&&homeMarketSummary!=null)homeMarketSummary.setText(txt);});});}
 private void showFinancial(){ screen=6;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(10));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showHome());h.addView(back,new LinearLayout.LayoutParams(dp(30),dp(42)));TextView logo=pill("✈",RED);h.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t(selectedSymbol,16,Color.WHITE,true));nm.addView(t(companyName(selectedTicker),9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));body.addView(h);addCompactLiveQuote();gap(6);
  LinearLayout tabs=new LinearLayout(this);String[] ts={"Genel","Grafik","Haber","KAP","Finansal"};for(int i=0;i<5;i++){TextView x=t(ts[i],10,i==4?Color.WHITE:MUTED,i==4);x.setGravity(Gravity.CENTER);final int k=i;x.setOnClickListener(v->{if(k==0)showDetail();else if(k==1)showChart();else if(k==2||k==3)showNews();else showFinancial();});tabs.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}body.addView(tabs);gap(8);
  LinearLayout sub=new LinearLayout(this);String[] st={"Özet","Gelir Tablosu","Bilanço","Nakit Akışı"};for(int i=0;i<4;i++){TextView x=pill(st[i],i==0?BLUE:PANEL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(30),1);lp.setMargins(dp(2),0,dp(2),0);sub.addView(x,lp);}body.addView(sub);gap(10);body.addView(t("Finansal & Değerleme",14,Color.WHITE,true));gap(5);financialData=t("Finansal veriler hazırlanıyor…",10,MUTED,false);financialData.setPadding(dp(10),dp(10),dp(10),dp(10));financialData.setBackground(bg(PANEL,8));body.addView(financialData);gap(6);body.addView(t("F/K, PD/DD, özkaynak, kâr ve temettü gibi bilanço oranları doğrulanmış temel veri kaynağı bağlanana kadar gösterilmez.",9,MUTED,false));loadFinancialSnapshot();
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);final int k=i;v.setOnClickListener(x->{if(k==0)showHome();else if(k==1)showMarkets();else if(k==2)showRadar();else if(k==3)showPortfolio();else showMore();});nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void loadFinancialSnapshot(){final String symbol=selectedSymbol;uiIo.execute(()->{try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(symbol,"2y","1d",520);if(d==null||d.size()<60)return;int n=d.size(),y=Math.max(0,n-252);double price=d.get(n-1).close,hi=-1e99,lo=1e99,sum=0,sum2=0,vol=0;for(int i=y;i<n;i++){MarketDataService.Candle x=d.get(i);hi=Math.max(hi,x.high);lo=Math.min(lo,x.low);sum+=x.close;sum2+=x.close*x.close;vol+=x.volume;}MarketDataService.Spot sp=MarketDataService.latestSpot(symbol);if(sp!=null&&sp.price>0)price=sp.price;int count=n-y;double avg=sum/count,var=Math.max(0,sum2/count-avg*avg),sd=Math.sqrt(var),fromLow=lo==0?0:(price/lo-1)*100,toHigh=price==0?0:(hi/price-1)*100,pos=hi==lo?50:(price-lo)/(hi-lo)*100;String txt=String.format(java.util.Locale.GERMANY,"Güncel fiyat       %.2f%s\n1Y ortalama        %.2f%s\n52H düşük          %.2f%s\n52H yüksek         %.2f%s\n52H konumu         %.0f%%\nDüşükten fark      %+.1f%%\nYükseğe mesafe    %+.1f%%\n1Y oynaklık (σ)   %.2f\nOrt. günlük hacim  %s\n\nTemel oranlar: veri kaynağı bekleniyor",price,currency(symbol),avg,currency(symbol),lo,currency(symbol),hi,currency(symbol),pos,fromLow,toHigh,sd,formatVolume(vol/count));runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&financialData!=null)financialData.setText(txt);});}catch(Exception ex){runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&financialData!=null)financialData.setText("Finansal/değerleme verisi alınamadı");});}});}
 private void showRadar(){ previousScreen=screen; screen=2; selectedSymbol=lastRadarSymbol;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(8));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showHome());h.addView(back,new LinearLayout.LayoutParams(dp(34),dp(42)));h.addView(t("Radar Taraması",18,Color.WHITE,true),new LinearLayout.LayoutParams(0,dp(42),1));h.addView(t("⌕",22,Color.WHITE,false),new LinearLayout.LayoutParams(dp(34),dp(42)));body.addView(h);gap(6);
  LinearLayout filters=new LinearLayout(this);String[] fs={"Tümü","AL Sinyali","İzle","SAT"};for(int i=0;i<fs.length;i++){final String filter=fs[i];TextView x=pill(fs[i],fs[i].equals(radarFilter)?BLUE:PANEL);x.setOnClickListener(v->{radarFilter=filter;renderRadarRows(cachedRadarRows);});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(32),1);lp.setMargins(dp(2),0,dp(2),0);filters.addView(x,lp);}body.addView(filters);gap(8);TextView scanState=t(scanDone?"Son tarama korunuyor • "+scanMode:"Henüz tarama yapılmadı",9,scanDone?GREEN:MUTED,true);body.addView(scanState);radarProgress=t("",9,BLUE,true);body.addView(radarProgress);gap(5);
  LinearLayout drops=new LinearLayout(this);String[] ds={selectedMarket+" ▾","Tüm Sektörler ▾","Teknik + Temel ▾"};for(String s:ds){TextView x=pill(s,PANEL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(34),1);lp.setMargins(dp(2),0,dp(2),0);drops.addView(x,lp);}body.addView(drops);gap(10);
  LinearLayout head=new LinearLayout(this);String[] hc={"Kod","Son Fiyat","Değişim","Sinyal"};for(String s:hc){TextView x=t(s,9,MUTED,true);x.setGravity(Gravity.CENTER);head.addView(x,new LinearLayout.LayoutParams(0,dp(28),1));}body.addView(head);
  radarRows=new LinearLayout(this);radarRows.setOrientation(LinearLayout.VERTICAL);body.addView(radarRows);if(cachedRadarRows.isEmpty())loadRadarCache(selectedMarket);
  if(!cachedRadarRows.isEmpty())renderRadarRows(cachedRadarRows);else radarRows.addView(t("Henüz tarama yapılmadı",11,MUTED,true));gap(8);TextView scanButton=pill(radarLoading?"TARANIYOR…":"TARAMAYI BAŞLAT",radarLoading?PANEL:BLUE);scanButton.setOnClickListener(v->{if(!radarLoading){radarRows.removeAllViews();renderRadarLoading();loadRadarRows();}});body.addView(scanButton,new LinearLayout.LayoutParams(-1,dp(44)));
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,i==2?BLUE:MUTED,i==2);v.setGravity(Gravity.CENTER);final int k=i;if(k==0)v.setOnClickListener(x->showHome());else if(k==1)v.setOnClickListener(x->showMarkets());else if(k==2)v.setOnClickListener(x->showRadar());else if(k==3)v.setOnClickListener(x->showPortfolio());else if(k==4)v.setOnClickListener(x->showMore());nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showTechnical(){ screen=7;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(8));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showDetail());h.addView(back,new LinearLayout.LayoutParams(dp(30),dp(42)));h.addView(pill("✈",RED),new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t(selectedSymbol,16,Color.WHITE,true));nm.addView(t(companyName(selectedTicker),9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));body.addView(h);addCompactLiveQuote();gap(8);
  LinearLayout techTitle=new LinearLayout(this);techTitle.setGravity(Gravity.CENTER_VERTICAL);techTitle.addView(t("İndikatör Sinyalleri",15,Color.WHITE,true),new LinearLayout.LayoutParams(0,dp(34),1));TextView target=pill("Hedef & Risk ›",BLUE);target.setOnClickListener(v->showTargetRisk());techTitle.addView(target,new LinearLayout.LayoutParams(dp(110),dp(32)));body.addView(techTitle);gap(5);LinearLayout hd=new LinearLayout(this);String[] hh={"İndikatör","Değer","Sinyal"};for(String s:hh){TextView x=t(s,9,MUTED,true);x.setGravity(Gravity.CENTER);hd.addView(x,new LinearLayout.LayoutParams(0,dp(28),1));}body.addView(hd);
  technicalRows=new TextView(this);technicalRows.setTextColor(Color.WHITE);technicalRows.setTextSize(10);technicalRows.setText("Gerçek indikatörler hesaplanıyor…");body.addView(technicalRows);gap(8);technicalSummary=t("Teknik görünüm hesaplanıyor…",13,MUTED,true);technicalSummary.setPadding(dp(12),dp(10),dp(12),dp(10));technicalSummary.setBackground(bg(PANEL,10));body.addView(technicalSummary);loadTechnicalIndicators();
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);final int k=i;v.setOnClickListener(x->{if(k==0)showHome();else if(k==1)showMarkets();else if(k==2)showRadar();else if(k==3)showPortfolio();else showMore();});nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void loadTechnicalIndicators(){final String symbol=selectedSymbol;uiIo.execute(()->{try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(symbol,"2y","1d",520);if(d==null||d.size()<60)return;int n=d.size(),e=n-1;double price=d.get(e).close,g=0,l=0,hi=-1e99,lo=1e99,tp=0,md=0,tr=0;for(int i=n-14;i<n;i++){double z=d.get(i).close-d.get(i-1).close;if(z>=0)g+=z;else l-=z;hi=Math.max(hi,d.get(i).high);lo=Math.min(lo,d.get(i).low);tp+=(d.get(i).high+d.get(i).low+d.get(i).close)/3d;tr+=Math.max(d.get(i).high-d.get(i).low,Math.max(Math.abs(d.get(i).high-d.get(i-1).close),Math.abs(d.get(i).low-d.get(i-1).close)));}double rsi=100-(100/(1+(l==0?100:g/l))),stoch=hi==lo?50:100*(price-lo)/(hi-lo),mtp=tp/14d;for(int i=n-14;i<n;i++)md+=Math.abs((d.get(i).high+d.get(i).low+d.get(i).close)/3d-mtp);md/=14d;double cci=md==0?0:(((d.get(e).high+d.get(e).low+price)/3d)-mtp)/(0.015*md),ema20=ema(d,20,e),ema50=ema(d,50,e),ema200=ema(d,200,e),macd=ema(d,12,e)-ema(d,26,e),atr=tr/14d;ShortPulseEngine.Result p=ShortPulseEngine.analyze(d,symbol,selectedProfile);String rows=String.format(java.util.Locale.GERMANY,"RSI(14)        %.1f   %s\nMACD           %.2f   %s\nStochastic     %.1f   %s\nCCI            %.1f   %s\nEMA20          %.2f   %s\nEMA50          %.2f   %s\nEMA200         %.2f   %s\nATR(14)        %.2f\nBRTV           %.1f\nBRM            %.2f\nBRH            %.1f",rsi,rsi<35?"AL":rsi>70?"SAT":"İZLE",macd,macd>0?"AL":"SAT",stoch,stoch<25?"AL":stoch>80?"SAT":"İZLE",cci,cci>100?"AL":cci<-100?"SAT":"İZLE",ema20,price>ema20?"AL":"SAT",ema50,price>ema50?"AL":"SAT",ema200,price>ema200?"AL":"SAT",atr,p.brtv,p.brm,p.brh);String sum=String.format(java.util.Locale.GERMANY,"Genel Teknik Görünüm: %s\nPulse %.1f • Güven %.0f%%\n%s",p.recommendation,p.score,p.confidence,p.phaseText);runOnUiThread(()->{if(!symbol.equals(selectedSymbol))return;if(technicalRows!=null)technicalRows.setText(rows);if(technicalSummary!=null){technicalSummary.setText(sum);technicalSummary.setTextColor(p.recommendation.contains("AL")?GREEN:p.recommendation.contains("SAT")?RED:AMBER);}});}catch(Exception ex){runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&technicalRows!=null)technicalRows.setText("Teknik veriler hesaplanamadı");});}});}
 private void loadTargetRisk(){final String symbol=selectedSymbol;uiIo.execute(()->{try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(symbol,"2y","1d",520);if(d==null||d.size()<60)return;int n=d.size(),e=n-1,start=Math.max(1,n-252);double price=d.get(e).close,hi=-1e99,lo=1e99,tr=0,sum=0,w=0;for(int i=start;i<n;i++){MarketDataService.Candle x=d.get(i);hi=Math.max(hi,x.high);lo=Math.min(lo,x.low);double wt=1d+(i-start)/(double)Math.max(1,n-start);sum+=x.close*wt;w+=wt;if(i>=n-14)tr+=Math.max(x.high-x.low,Math.max(Math.abs(x.high-d.get(i-1).close),Math.abs(x.low-d.get(i-1).close)));}MarketDataService.Spot sp=MarketDataService.latestSpot(symbol);if(sp!=null&&sp.price>0)price=sp.price;double atr=tr/14d;ShortPulseEngine.Result pulse=ShortPulseEngine.analyze(d,symbol,selectedProfile);double adj=Math.max(-.12,Math.min(.12,(pulse.score-50d)/250d)),paper=Math.max(lo,Math.min(hi,(sum/w)*(1+adj)));double support=Math.max(lo,price-2*atr),resistance=Math.min(hi,price+2*atr),stop=Math.max(lo,price-2.5*atr),t1=Math.max(price+atr,paper),t2=Math.max(t1,Math.min(hi,price+3*atr));double rr=(price-stop)<=0?0:(t1-price)/(price-stop),gap=price==0?0:(paper/price-1)*100;String txt=String.format(java.util.Locale.GERMANY,"Güncel          %.2f%s\nKağıt değeri    %.2f%s  (%+.1f%%)\nDestek          %.2f%s\nDirenç          %.2f%s\nHedef 1         %.2f%s\nHedef 2         %.2f%s\nStop referansı  %.2f%s\nATR(14)         %.2f\nRisk/Getiri     1 : %.2f\n\nBorsaPulse: %s • %.0f%% güven",price,currency(symbol),paper,currency(symbol),gap,support,currency(symbol),resistance,currency(symbol),t1,currency(symbol),t2,currency(symbol),stop,currency(symbol),atr,rr,pulse.recommendation,pulse.confidence);runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&targetRiskData!=null){targetRiskData.setText(txt);targetRiskData.setTextColor(gap>=12?GREEN:gap<=-10?RED:Color.WHITE);}});}catch(Exception ex){runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&targetRiskData!=null)targetRiskData.setText("Hedef/risk verisi hesaplanamadı");});}});}
 private void showTargetRisk(){ screen=8;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(8));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showDetail());h.addView(back,new LinearLayout.LayoutParams(dp(30),dp(42)));h.addView(pill("✈",RED),new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout nm=new LinearLayout(this);nm.setOrientation(LinearLayout.VERTICAL);nm.addView(t(selectedSymbol,16,Color.WHITE,true));nm.addView(t(companyName(selectedTicker),9,MUTED,false));h.addView(nm,new LinearLayout.LayoutParams(0,dp(44),1));body.addView(h);addCompactLiveQuote();gap(8);
  body.addView(t("Dinamik Hedef & Risk",15,Color.WHITE,true));gap(5);targetRiskData=t("Hedefler gerçek fiyat geçmişinden hesaplanıyor…",11,MUTED,true);targetRiskData.setPadding(dp(12),dp(12),dp(12),dp(12));targetRiskData.setBackground(bg(PANEL,9));body.addView(targetRiskData);gap(8);body.addView(t("Not: Bunlar analist hedef fiyatları değildir. Fiyat geçmişi, ATR, trend ve BorsaPulse verilerinden türetilen teknik seviyelerdir.",9,MUTED,false));gap(8);loadTargetRisk();
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);final int k=i;if(k==0)v.setOnClickListener(x->showHome());else if(k==2)v.setOnClickListener(x->showRadar());nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showPortfolio(){ previousScreen=screen; screen=9;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(8));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showHome());h.addView(back,new LinearLayout.LayoutParams(dp(34),dp(42)));h.addView(t("Portföyüm",18,Color.WHITE,true),new LinearLayout.LayoutParams(0,dp(42),1));h.addView(t("⋮",22,Color.WHITE,true),new LinearLayout.LayoutParams(dp(34),dp(42)));body.addView(h);
  gap(4);body.addView(t("Toplam Değer",10,MUTED,false));body.addView(t("482.650 ₺",28,Color.WHITE,true));body.addView(t("+12.340 ₺  (+2,62%)  Bugün",12,GREEN,true));gap(8);
  LinearLayout tabs=new LinearLayout(this);TextView p1=pill("Portföy",BLUE),p2=pill("İşlemler",PANEL);tabs.addView(p1,new LinearLayout.LayoutParams(0,dp(34),1));tabs.addView(p2,new LinearLayout.LayoutParams(0,dp(34),1));body.addView(tabs);gap(8);
  LinearLayout hd=new LinearLayout(this);String[] hh={"Hisse","Adet","Ort. Maliyet","Güncel","K/Z"};for(String s:hh){TextView x=t(s,8,MUTED,true);x.setGravity(Gravity.CENTER);hd.addView(x,new LinearLayout.LayoutParams(0,dp(28),1));}body.addView(hd);
  String[][] rows={{"THYAO","500","220,50","277,20","+%25,7"},{"BIMAS","200","260,10","287,50","+%10,5"},{"TCELL","1.000","65,30","71,24","+%9,1"},{"PETKM","2.000","19,80","20,08","+%1,4"},{"NVDA","10","150,20","177,26","+%18,0"}};
  for(String[] q:rows){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(2),dp(3),dp(2),dp(3));for(int i=0;i<5;i++){TextView x=t(q[i],9,i==4?GREEN:Color.WHITE,i==0);x.setGravity(Gravity.CENTER);if(i==0)x.setOnClickListener(v->{selectedSymbol=q[0];showDetail();});row.addView(x,new LinearLayout.LayoutParams(0,dp(38),1));}body.addView(row);}
  gap(6);LinearLayout total=new LinearLayout(this);total.setPadding(dp(8),dp(8),dp(8),dp(8));total.setBackground(bg(PANEL,8));total.addView(t("Toplam K/Z",11,MUTED,true),new LinearLayout.LayoutParams(0,dp(30),1));TextView tv=t("+73.850 ₺  (+18,0%)",12,GREEN,true);tv.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);total.addView(tv,new LinearLayout.LayoutParams(dp(180),dp(30)));body.addView(total);gap(10);
  LinearLayout acts=new LinearLayout(this);TextView add=pill("+ Hisse Ekle",BLUE);TextView analyze=pill("Portföy Analiz",PANEL);add.setOnClickListener(v->showAddStockDialog());analyze.setOnClickListener(v->showTechnical());LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(0,dp(42),1);ap.setMargins(dp(2),0,dp(2),0);acts.addView(add,ap);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(42),1);bp.setMargins(dp(2),0,dp(2),0);acts.addView(analyze,bp);body.addView(acts);
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,i==3?BLUE:MUTED,i==3);v.setGravity(Gravity.CENTER);final int k=i;if(k==0)v.setOnClickListener(x->showHome());else if(k==2)v.setOnClickListener(x->showRadar());else if(k==3)v.setOnClickListener(x->showPortfolio());nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showStrategy(){ screen=10;
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(10),dp(12),dp(8));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showHome());h.addView(back,new LinearLayout.LayoutParams(dp(34),dp(42)));h.addView(t("Strateji Seç",18,Color.WHITE,true),new LinearLayout.LayoutParams(0,dp(42),1));body.addView(h);gap(8);
  String[][] cards={{"⚡  Kısa Vade","Günlük ve saatlik fırsatları teknik sinyallerle tara."},{"◆  Temettü","Düzenli temettü ve finansal güç potansiyelini değerlendir."},{"↗  Uzun Vade","Temel değerleme ve uzun vadeli büyüme fırsatlarını tara."}};int[] cc={GREEN,BLUE,Color.rgb(128,86,210)};for(int i=0;i<cards.length;i++){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(12),dp(14),dp(12));card.setBackground(bg(cc[i],10));card.addView(t(cards[i][0],15,Color.WHITE,true));card.addView(t(cards[i][1],10,Color.WHITE,false));body.addView(card,new LinearLayout.LayoutParams(-1,dp(76)));gap(7);}
  gap(5);body.addView(t("Tarama Kriterleri",14,Color.WHITE,true));String[] criteria={"Teknik Analiz","Temel Analiz","Haber Taraması","Sektör Analizi","Büyük Alıcı/Satıcı","Finansal Güç","Temettü Potansiyeli"};for(String s:criteria){android.widget.CheckBox cb=new android.widget.CheckBox(this);cb.setText(s);cb.setTextColor(Color.WHITE);cb.setTextSize(11);cb.setChecked(true);cb.setButtonTintList(android.content.res.ColorStateList.valueOf(BLUE));body.addView(cb,new LinearLayout.LayoutParams(-1,dp(38)));}
  gap(8);TextView start=pill("Taramayı Başlat",GREEN);start.setTextSize(13);start.setOnClickListener(v->{scanDone=true;scanMode="Teknik + Temel";cachedRadarRows.clear();getSharedPreferences("borsaradar",MODE_PRIVATE).edit().putBoolean("scanDone",true).putString("scanMode",scanMode).apply();showRadar();});body.addView(start,new LinearLayout.LayoutParams(-1,dp(48)));
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,27,46));String[] nn={"⌂\nAna Sayfa","▥\nPiyasalar","◎\nRadar","▣\nPortföy","•••\nDiğer"};for(int i=0;i<5;i++){TextView v=t(nn[i],9,MUTED,false);v.setGravity(Gravity.CENTER);final int k=i;if(k==0)v.setOnClickListener(x->showHome());else if(k==2)v.setOnClickListener(x->showRadar());else if(k==3)v.setOnClickListener(x->showPortfolio());nav.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));}root.addView(nav);setContentView(root);
 }

 private void showMore(){ previousScreen=screen; screen=11;
  LinearLayout root=detailRoot();body.addView(t("Diğer",20,Color.WHITE,true));gap(8);LinearLayout profile=card();profile.addView(t("EK   Erdogan Kulanoglu",15,Color.WHITE,true));profile.addView(t("Pro Hesap",10,BLUE,true));body.addView(profile);gap(8);
  String[] items={"Piyasa Takvimi","Sektörler","Favorilerim","Alarmlar","Hisse Karşılaştırma","Döviz / Altın / Emtia","Ekonomik Veriler","Ayarlar","Yardım & Destek","Hakkında"};for(String s:items){TextView v=t(s+"   ›",12,Color.WHITE,false);v.setPadding(dp(12),0,dp(12),0);v.setBackground(bg(PANEL,8));v.setOnClickListener(x->Toast.makeText(this,s+" açılacak",Toast.LENGTH_SHORT).show());body.addView(v,new LinearLayout.LayoutParams(-1,dp(42)));gap(3);}TextView out=pill("Çıkış Yap",RED);body.addView(out,new LinearLayout.LayoutParams(-1,dp(42)));nav(root,4);setContentView(root);
 }

 private void renderRadarLoading(){if(radarRows==null)return;radarRows.removeAllViews();for(String s:radarSymbols){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);String[] a={s,"…","…","…"};for(int i=0;i<4;i++){TextView x=t(a[i],10,i==0?Color.WHITE:MUTED,i==0);x.setGravity(Gravity.CENTER);row.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}radarRows.addView(row);}}
 private String[] analyzeRadarSymbol(String s){try{
  java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(s,"2y","1d",520);if(d==null||d.size()<60)return null;
  int n=d.size(),end=n-1;double price=d.get(end).close,prev=d.get(end-1).close;MarketDataService.Spot sp=MarketDataService.latestSpot(s);if(sp!=null&&sp.price>0)price=sp.price;
  ShortPulseEngine.Result pulse=ShortPulseEngine.analyze(d,s,selectedProfile);
  int y1=Math.max(0,n-252);double sum1=0,sum2=0,w=0,weighted=0,hi=d.get(y1).high,lo=d.get(y1).low;
  for(int i=y1;i<n;i++){double cl=d.get(i).close;sum1+=cl;double wt=1d+(i-y1)/(double)Math.max(1,n-y1);weighted+=cl*wt;w+=wt;hi=Math.max(hi,d.get(i).high);lo=Math.min(lo,d.get(i).low);}
  for(int i=0;i<n;i++)sum2+=d.get(i).close;
  double avg1=sum1/(n-y1),avg2=sum2/n,technicalAdj=Math.max(-0.12,Math.min(0.12,(pulse.score-50d)/250d)),paper=Math.max(lo,Math.min(hi,(weighted/w)*(1d+technicalAdj)));
  double disc1=avg1==0?0:(price/avg1-1d)*100d,disc2=avg2==0?0:(price/avg2-1d)*100d,paperGap=price==0?0:(paper/price-1d)*100d;
  int valueScore=0;if(disc1<=-20)valueScore+=2;else if(disc1<=-10)valueScore++;else if(disc1>=20)valueScore--;if(disc2<=-20)valueScore+=2;else if(disc2<=-10)valueScore++;else if(disc2>=20)valueScore--;if(paperGap>=25)valueScore+=2;else if(paperGap>=12)valueScore++;else if(paperGap<=-15)valueScore--;
  int pulseScore=(int)Math.round((pulse.score-50d)/10d);int total=Math.max(-8,Math.min(8,pulseScore+valueScore));
  boolean broken=pulse.recommendation.contains("SAT")&&pulse.score<35;String sig=(!broken&&total>=3)?"AL":(total<=-3?"SAT":"İZLE");
  int confidence=Math.min(97,Math.max(50,(int)Math.round(pulse.confidence)+Math.abs(valueScore)*3));double pct=prev==0?0:(price-prev)/prev*100d;
  String note=String.format(java.util.Locale.GERMANY,"Güven %d%% • %s\nKağıt %.2f%s (%+.1f%%) • 1Y ort %.2f%s (%+.1f%%) • 2Y ort %.2f%s (%+.1f%%)\nBRTV %.1f • BRM %.2f • BRH %.1f",confidence,pulse.recommendation,paper,currency(s),paperGap,avg1,currency(s),disc1,avg2,currency(s),disc2,pulse.brtv,pulse.brm,pulse.brh);
  return new String[]{s,String.format(java.util.Locale.GERMANY,"%.2f",price),String.format(java.util.Locale.GERMANY,"%+.2f%%",pct),sig,String.valueOf(total),note,String.valueOf(confidence),pulse.recommendation,valueScore>=2?"UCUZ":valueScore<=-2?"PAHALI":"NORMAL",String.format(java.util.Locale.GERMANY,"%.1f",paperGap)};
 }catch(Exception ex){return null;}}
 private void loadRadarRows(){if(radarLoading)return;radarLoading=true;final String scanMarket=selectedMarket;if(radarProgress!=null)radarProgress.setText("Tarama hazırlanıyor • "+scanMarket);final String[] symbols=radarUniverse().clone();final java.util.concurrent.ExecutorService pool=java.util.concurrent.Executors.newFixedThreadPool(Math.min(10,Math.max(4,Runtime.getRuntime().availableProcessors()*2)));final java.util.concurrent.ConcurrentLinkedQueue<String[]> out=new java.util.concurrent.ConcurrentLinkedQueue<>();final java.util.concurrent.atomic.AtomicInteger done=new java.util.concurrent.atomic.AtomicInteger();for(String sym:symbols){pool.execute(()->{String[] row=analyzeRadarSymbol(sym);if(row!=null)out.add(row);int x=done.incrementAndGet();runOnUiThread(()->{if(radarProgress!=null&&screen==2&&scanMarket.equals(selectedMarket))radarProgress.setText("Tarama: "+x+"/"+symbols.length+"  %"+Math.round(x*100f/symbols.length));});if(x==symbols.length){pool.shutdown();final java.util.ArrayList<String[]> result=new java.util.ArrayList<>(out);java.util.Collections.sort(result,(a,b)->Integer.compare(Integer.parseInt(b[4]),Integer.parseInt(a[4])));runOnUiThread(()->{radarLoading=false;radarCacheByMarket.put(scanMarket,new java.util.ArrayList<>(result));saveRadarCache(scanMarket,result);scanDoneByMarket.put(scanMarket,true);getSharedPreferences("borsaradar",MODE_PRIVATE).edit().putBoolean("scanDone_"+scanMarket,true).apply();if(scanMarket.equals(selectedMarket)){cachedRadarRows.clear();cachedRadarRows.addAll(result);scanDone=true;if(radarProgress!=null)radarProgress.setText("Tarama tamamlandı • "+result.size()+" hisse • "+MarketDataService.healthySourceCount()+"/"+MarketDataService.activeSourceCount()+" aktif kaynak");renderRadarRows(cachedRadarRows);}});}});}}
 private void renderRadarRows(java.util.List<String[]> rows){if(radarRows==null||screen!=2)return;radarRows.removeAllViews();for(String[] q:rows){if(q==null||q.length<4)continue;if("AL Sinyali".equals(radarFilter)&&!"AL".equals(q[3]))continue;if("İzle".equals(radarFilter)&&!"İZLE".equals(q[3]))continue;if("SAT".equals(radarFilter)&&!"SAT".equals(q[3]))continue;LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(2),dp(3),dp(2),dp(3));for(int i=0;i<4;i++){int col=i==2?(q[i].startsWith("-")?RED:GREEN):Color.WHITE;String cell=q[i];if(i==3&&q.length>8)cell=q[i]+" • "+q[8];TextView x=i==3?pill(cell+(q.length>6?" "+q[6]+"%":""),q[i].equals("AL")?GREEN:q[i].equals("SAT")?RED:AMBER):t(cell,10,col,i==0);x.setGravity(Gravity.CENTER);final String sym=q[0];if(i==0){x.setOnLongClickListener(v->{Toast.makeText(this,q.length>5?q[5]:"",Toast.LENGTH_LONG).show();return true;});x.setOnClickListener(v->{selectedSymbol=sym;lastRadarSymbol=sym;getSharedPreferences("borsaradar",MODE_PRIVATE).edit().putString("lastRadarSymbol",sym).apply();showDetail();});}row.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}radarRows.addView(row);}if(radarRows.getChildCount()==0)radarRows.addView(t("Bu filtrede sonuç yok",11,MUTED,true));}
 private void loadLiveQuote(){ final String symbol=selectedSymbol; uiIo.execute(()->{try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(symbol,"5d","5m",400);if(d==null||d.size()<2)return;MarketDataService.Candle last=d.get(d.size()-1),prev=d.get(d.size()-2);double spot=last.close;MarketDataService.Spot sp=MarketDataService.latestSpot(symbol);if(sp!=null&&sp.price>0)spot=sp.price;double hi=last.high,lo=last.low,vol=last.volume; for(int i=Math.max(0,d.size()-80);i<d.size();i++){MarketDataService.Candle x=d.get(i);hi=Math.max(hi,x.high);lo=Math.min(lo,x.low);vol+=i==d.size()-1?0:x.volume;} final double price=spot,base=prev.close,chg=price-base,pct=base==0?0:(chg/base*100.0),open=last.open,high=hi,low=lo,volume=vol;final long tm=last.time;runOnUiThread(()->{if(!symbol.equals(selectedSymbol)||livePrice==null)return;livePrice.setText(String.format(java.util.Locale.GERMANY,"%.2f%s",price,currency(symbol)));liveChange.setText(String.format(java.util.Locale.GERMANY,"%+.2f  (%+.2f%%)",chg,pct));liveChange.setTextColor(chg>=0?GREEN:RED);liveTime.setText(new java.text.SimpleDateFormat("dd.MM.yyyy HH:mm",java.util.Locale.GERMANY).format(new java.util.Date(tm*1000L))+" • "+MarketDataService.sourceFor(symbol,"5d","5m"));setLiveStats(new double[]{open,high,low,volume});});}catch(Exception e){runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&livePrice!=null)livePrice.setText("Fiyat alınamadı");});}});}
 private void loadPaperValue(){final String symbol=selectedSymbol;uiIo.execute(()->{try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(symbol,"2y","1d",520);if(d==null||d.size()<120)return;int n=d.size();double now=d.get(n-1).close,sum=0,w=0;int start=Math.max(0,n-252);for(int i=start;i<n;i++){double weight=1d+(i-start)/(double)Math.max(1,n-start);sum+=d.get(i).close*weight;w+=weight;}double weightedAvg=sum/w;double hi=d.get(start).high,lo=d.get(start).low;for(int i=start;i<n;i++){hi=Math.max(hi,d.get(i).high);lo=Math.min(lo,d.get(i).low);}ShortPulseEngine.Result r=ShortPulseEngine.analyze(d,symbol,selectedProfile);double technicalAdj=Math.max(-0.12,Math.min(0.12,(r.score-50d)/250d));double paper=weightedAvg*(1d+technicalAdj);paper=Math.max(lo,Math.min(hi,paper));double upside=now==0?0:(paper/now-1d)*100d;String state=upside>=25?"ÇOK UCUZ":upside>=12?"UCUZ":upside<=-20?"PAHALI":upside<=-10?"YÜKSEK":"DENGE";final String txt=String.format(java.util.Locale.GERMANY,"Kağıt değeri* %.2f%s • Fark %+.1f%% • %s",paper,currency(symbol),upside,state);runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&paperValue!=null){paperValue.setText(txt);paperValue.setTextColor(upside>=12?GREEN:upside<=-10?RED:AMBER);}});}catch(Exception e){runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&paperValue!=null)paperValue.setText("Kağıt değeri hesaplanamadı");});}});}
 private void loadValueHistory(){final String symbol=selectedSymbol;uiIo.execute(()->{try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(symbol,"2y","1d",520);if(d==null||d.size()<40)return;int n=d.size();double now=d.get(n-1).close;int y1=Math.max(0,n-252),y2=0;double p1=d.get(y1).close,p2=d.get(y2).close,sum1=0,sum2=0;for(int i=y1;i<n;i++)sum1+=d.get(i).close;for(int i=0;i<n;i++)sum2+=d.get(i).close;double a1=sum1/(n-y1),a2=sum2/n;double discount1=a1==0?0:(now/a1-1)*100,discount2=a2==0?0:(now/a2-1)*100;String valueSignal=(discount1<=-20&&discount2<=-20)?"DEĞERSEL AL":(discount1<=-10||discount2<=-15)?"UCUZ / İZLE":(discount1>=20&&discount2>=20)?"PAHALI":"NORMAL";final String txt=String.format(java.util.Locale.GERMANY,"1Y önce %.2f%s • 1Y ort. %.2f%s (%+.1f%%)\n2Y önce %.2f%s • 2Y ort. %.2f%s (%+.1f%%) • %s",p1,currency(symbol),a1,currency(symbol),discount1,p2,currency(symbol),a2,currency(symbol),discount2,valueSignal);runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&valueHistory!=null){valueHistory.setText(txt);valueHistory.setTextColor(valueSignal.contains("AL")?GREEN:valueSignal.equals("PAHALI")?RED:AMBER);}});}catch(Exception e){runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&valueHistory!=null)valueHistory.setText("Değer geçmişi alınamadı");});}});}
 private double ema(java.util.List<MarketDataService.Candle>d,int p,int end){double k=2d/(p+1d),e=d.get(Math.max(0,end-p+1)).close;for(int i=Math.max(0,end-p+2);i<=end;i++)e=d.get(i).close*k+e*(1-k);return e;}
 private void loadComputedSignal(){final String symbol=selectedSymbol;uiIo.execute(()->{try{
  java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(symbol,"6mo","1d",180);
  if(d==null||d.size()<35)return;
  ShortPulseEngine.Result p=ShortPulseEngine.analyze(d,symbol,selectedProfile);
  final String sig=p.recommendation.contains("SAT")?"SAT":p.recommendation.contains("AL")?"AL":"TUT";
  final String text=String.format(java.util.Locale.GERMANY,
    "Model: %s • Pulse %.1f • Güven %.0f%%\nBRTV %.1f • BRM %.2f • BRH %.1f\n%s",
    p.recommendation,p.score,p.confidence,p.brtv,p.brm,p.brh,p.phaseText);
  runOnUiThread(()->{if(!symbol.equals(selectedSymbol)||computedSignal==null)return;
    computedSignal.setText(text);computedSignal.setTextColor("AL".equals(sig)?GREEN:"SAT".equals(sig)?RED:AMBER);
  });
 }catch(Exception e){runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&computedSignal!=null)computedSignal.setText("Sinyal hesaplanamadı");});}});}
 private void renderHorizonSignals(String shortSig,String mediumSig,String longSig){if(horizonSignals==null)return;horizonSignals.removeAllViews();String[][] a={{"Kısa",shortSig},{"Orta",mediumSig},{"Uzun",longSig}};for(String[] q:a){LinearLayout z=card();z.setGravity(Gravity.CENTER);TextView h=t(q[0],9,MUTED,true),v=t(q[1],12,"AL".equals(q[1])?GREEN:"SAT".equals(q[1])?RED:AMBER,true);h.setGravity(Gravity.CENTER);v.setGravity(Gravity.CENTER);z.addView(h);z.addView(v);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(54),1);lp.setMargins(dp(2),dp(2),dp(2),dp(2));horizonSignals.addView(z,lp);}}
 private void loadChartQuote(){final String symbol=selectedSymbol;uiIo.execute(()->{try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(symbol,"5d","5m",400);if(d==null||d.size()<2)return;MarketDataService.Candle last=d.get(d.size()-1),prev=d.get(d.size()-2);double spot=last.close;MarketDataService.Spot sp=MarketDataService.latestSpot(symbol);if(sp!=null&&sp.price>0)spot=sp.price;final double price=spot,chg=spot-prev.close,pct=prev.close==0?0:(chg/prev.close*100d);runOnUiThread(()->{if(!symbol.equals(selectedSymbol)||chartPrice==null)return;chartPrice.setText(String.format(java.util.Locale.GERMANY,"%.2f%s",price,currency(symbol)));chartChange.setText(String.format(java.util.Locale.GERMANY,"%+.2f  (%+.2f%%)",chg,pct));chartChange.setTextColor(chg>=0?GREEN:RED);});}catch(Exception e){runOnUiThread(()->{if(symbol.equals(selectedSymbol)&&chartPrice!=null)chartPrice.setText("Fiyat alınamadı");});}});}
 private void setLiveStats(double[] v){if(liveStats==null)return;liveStats.removeAllViews();String[] ss;if(v==null)ss=new String[]{"Açılış\n—","Yüksek\n—","Düşük\n—","Hacim\n—"};else ss=new String[]{String.format(java.util.Locale.GERMANY,"Açılış\n%.2f",v[0]),String.format(java.util.Locale.GERMANY,"Yüksek\n%.2f",v[1]),String.format(java.util.Locale.GERMANY,"Düşük\n%.2f",v[2]),"Hacim\n"+formatVolume(v[3])};for(String s:ss){TextView x=t(s,9,Color.WHITE,false);x.setGravity(Gravity.CENTER);liveStats.addView(x,new LinearLayout.LayoutParams(0,dp(48),1));}}
 private String formatVolume(double v){if(v>=1000000000)return String.format(java.util.Locale.GERMANY,"%.1f Mr",v/1000000000d);if(v>=1000000)return String.format(java.util.Locale.GERMANY,"%.1f M",v/1000000d);if(v>=1000)return String.format(java.util.Locale.GERMANY,"%.1f B",v/1000d);return String.format(java.util.Locale.GERMANY,"%.0f",v);}
 private void syncRadarIndex(){for(int i=0;i<radarSymbols.length;i++)if(radarSymbols[i].equals(selectedSymbol)){radarIndex=i;return;}}
 private void moveRadar(int delta){syncRadarIndex();radarIndex=(radarIndex+delta+radarSymbols.length)%radarSymbols.length;selectedSymbol=radarSymbols[radarIndex];lastRadarSymbol=selectedSymbol;getSharedPreferences("borsaradar",MODE_PRIVATE).edit().putString("lastRadarSymbol",selectedSymbol).apply();showDetail();}

 private void showAddStockDialog(){
  LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),dp(8),dp(20),0);
  EditText ticker=new EditText(this);ticker.setHint("Hisse kodu (örn. THYAO)");EditText qty=new EditText(this);qty.setHint("Adet");qty.setInputType(2);EditText cost=new EditText(this);cost.setHint("Alış fiyatı");cost.setInputType(8194);box.addView(ticker);box.addView(qty);box.addView(cost);
  new android.app.AlertDialog.Builder(this).setTitle("Portföye Hisse Ekle").setView(box).setNegativeButton("İptal",null).setPositiveButton("Ekle",(d,w)->{String s=ticker.getText().toString().trim().toUpperCase();if(s.length()==0)Toast.makeText(this,"Hisse kodu gerekli",Toast.LENGTH_SHORT).show();else Toast.makeText(this,s+" portföye eklendi",Toast.LENGTH_SHORT).show();}).show();
 }

 private void loadRealChart(String period){
  final String[] range={"1d"},interval={"5m"};if("1H".equals(period)){range[0]="5d";interval[0]="5m";}else if("1A".equals(period)){range[0]="1mo";interval[0]="1d";}else if("3A".equals(period)){range[0]="3mo";interval[0]="1d";}else if("6A".equals(period)){range[0]="6mo";interval[0]="1d";}else if("1Y".equals(period)){range[0]="1y";interval[0]="1d";}else if("2Y".equals(period)){range[0]="2y";interval[0]="1d";}
  Toast.makeText(this,period+" verisi yükleniyor",Toast.LENGTH_SHORT).show();uiIo.execute(()->{try{java.util.List<MarketDataService.Candle>d=MarketDataService.fetchSeries(selectedSymbol,range[0],interval[0],180);runOnUiThread(()->showLiveChart(period,d));}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Grafik verisi alınamadı",Toast.LENGTH_SHORT).show());}});
 }
 private void showLiveChart(String period,java.util.List<MarketDataService.Candle>d){
  if(d==null||d.size()<2)return;LinearLayout root=detailRoot();LinearLayout h=new LinearLayout(this);TextView back=t("‹",24,Color.WHITE,true);back.setOnClickListener(v->showChart());h.addView(back,new LinearLayout.LayoutParams(dp(32),dp(42)));h.addView(t(selectedSymbol+" • "+period,17,Color.WHITE,true),new LinearLayout.LayoutParams(0,dp(42),1));body.addView(h);PriceChartView chart=new PriceChartView(this,d,period);body.addView(chart,new LinearLayout.LayoutParams(-1,dp(430)));TextView tech=pill("Teknik Analiz",BLUE);tech.setOnClickListener(v->showTechnical());body.addView(tech,new LinearLayout.LayoutParams(-1,dp(44)));nav(root,0);setContentView(root);
 }
 private String companyName(String s){if("BIMAS".equals(s))return "BİM Birleşik Mağazalar A.Ş.";if("TCELL".equals(s))return "Turkcell İletişim Hizmetleri A.Ş.";if("ASELS".equals(s))return "ASELSAN Elektronik Sanayi ve Ticaret A.Ş.";if("KRDMD".equals(s))return "Kardemir D";if("PETKM".equals(s))return "Petkim Petrokimya Holding A.Ş.";if("KCHOL".equals(s))return "Koç Holding A.Ş.";if("TUPRS".equals(s))return "Tüpraş";if("GARAN".equals(s))return "Garanti BBVA";if("AKBNK".equals(s))return "Akbank";if("YKBNK".equals(s))return "Yapı Kredi";if("SASA".equals(s))return "SASA Polyester";if("NVDA".equals(s))return "NVIDIA Corporation";return "Türk Hava Yolları A.Ş.";}\n
 private static String encRadar(String s){try{return android.util.Base64.encodeToString((s==null?"":s).getBytes("UTF-8"),android.util.Base64.NO_WRAP);}catch(Exception e){return "";}}
 private static String decRadar(String s){try{return new String(android.util.Base64.decode(s,android.util.Base64.NO_WRAP),"UTF-8");}catch(Exception e){return "";}}
  private void saveRadarCache(String market,java.util.List<String[]> rows){java.util.ArrayList<String[]> keep=new java.util.ArrayList<>(cachedRadarRows);cachedRadarRows.clear();cachedRadarRows.addAll(rows);saveRadarCache(market);cachedRadarRows.clear();cachedRadarRows.addAll(keep);}\nprivate void saveRadarCache(String market){
  if(market==null)return;java.util.ArrayList<String[]> rows=radarCacheByMarket.get(market);if(rows==null)rows=cachedRadarRows;
  StringBuilder b=new StringBuilder();for(String[] r:rows){if(b.length()>0)b.append("\n");for(int i=0;i<r.length;i++){if(i>0)b.append(".");b.append(encRadar(r[i]));}}
  getSharedPreferences("borsaradar",MODE_PRIVATE).edit().putString("radar_rows_"+market,b.toString()).putBoolean("scanDone_"+market,!rows.isEmpty()).apply();
 }
 private void loadRadarCache(String market){
  cachedRadarRows.clear();String raw=getSharedPreferences("borsaradar",MODE_PRIVATE).getString("radar_rows_"+market,"");
  if(!raw.isEmpty())for(String line:raw.split("\\n")){String[] p=line.split("\\.",-1);String[] r=new String[p.length];for(int i=0;i<p.length;i++)r[i]=decRadar(p[i]);cachedRadarRows.add(r);}
  radarCacheByMarket.put(market,new java.util.ArrayList<>(cachedRadarRows));scanDone=!cachedRadarRows.isEmpty();scanDoneByMarket.put(market,scanDone);
 }
}
